package com.pinde.sci.model.mo;

import com.pinde.core.model.MybatisObject;

public class EdcElement extends MybatisObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_ELEMENT.ELEMENT_FLOW
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	private String elementFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_ELEMENT.ELEMENT_NAME
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	private String elementName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_ELEMENT.ELEMENT_CODE
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	private String elementCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_ELEMENT.ELEMENT_VAR_NAME
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	private String elementVarName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_ELEMENT.MODULE_CODE
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	private String moduleCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_ELEMENT.ELEMENT_SERIAL
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	private String elementSerial;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_ELEMENT.COLUMN_COUNT
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	private String columnCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_ELEMENT.ORDINAL
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	private Integer ordinal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_ELEMENT.PROJ_FLOW
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	private String projFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_ELEMENT.RECORD_STATUS
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	private String recordStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_ELEMENT.CREATE_TIME
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_ELEMENT.CREATE_USER_FLOW
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	private String createUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_ELEMENT.MODIFY_TIME
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	private String modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_ELEMENT.MODIFY_USER_FLOW
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	private String modifyUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_ELEMENT.FIXED_WIDTH
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	private String fixedWidth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_ELEMENT.IS_VIEW_NAME
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	private String isViewName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_ELEMENT.ELEMENT_FLOW
	 * @return  the value of PDSCI.EDC_ELEMENT.ELEMENT_FLOW
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public String getElementFlow() {
		return elementFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_ELEMENT.ELEMENT_FLOW
	 * @param elementFlow  the value for PDSCI.EDC_ELEMENT.ELEMENT_FLOW
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public void setElementFlow(String elementFlow) {
		this.elementFlow = elementFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_ELEMENT.ELEMENT_NAME
	 * @return  the value of PDSCI.EDC_ELEMENT.ELEMENT_NAME
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public String getElementName() {
		return elementName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_ELEMENT.ELEMENT_NAME
	 * @param elementName  the value for PDSCI.EDC_ELEMENT.ELEMENT_NAME
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public void setElementName(String elementName) {
		this.elementName = elementName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_ELEMENT.ELEMENT_CODE
	 * @return  the value of PDSCI.EDC_ELEMENT.ELEMENT_CODE
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public String getElementCode() {
		return elementCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_ELEMENT.ELEMENT_CODE
	 * @param elementCode  the value for PDSCI.EDC_ELEMENT.ELEMENT_CODE
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public void setElementCode(String elementCode) {
		this.elementCode = elementCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_ELEMENT.ELEMENT_VAR_NAME
	 * @return  the value of PDSCI.EDC_ELEMENT.ELEMENT_VAR_NAME
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public String getElementVarName() {
		return elementVarName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_ELEMENT.ELEMENT_VAR_NAME
	 * @param elementVarName  the value for PDSCI.EDC_ELEMENT.ELEMENT_VAR_NAME
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public void setElementVarName(String elementVarName) {
		this.elementVarName = elementVarName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_ELEMENT.MODULE_CODE
	 * @return  the value of PDSCI.EDC_ELEMENT.MODULE_CODE
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public String getModuleCode() {
		return moduleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_ELEMENT.MODULE_CODE
	 * @param moduleCode  the value for PDSCI.EDC_ELEMENT.MODULE_CODE
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public void setModuleCode(String moduleCode) {
		this.moduleCode = moduleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_ELEMENT.ELEMENT_SERIAL
	 * @return  the value of PDSCI.EDC_ELEMENT.ELEMENT_SERIAL
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public String getElementSerial() {
		return elementSerial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_ELEMENT.ELEMENT_SERIAL
	 * @param elementSerial  the value for PDSCI.EDC_ELEMENT.ELEMENT_SERIAL
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public void setElementSerial(String elementSerial) {
		this.elementSerial = elementSerial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_ELEMENT.COLUMN_COUNT
	 * @return  the value of PDSCI.EDC_ELEMENT.COLUMN_COUNT
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public String getColumnCount() {
		return columnCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_ELEMENT.COLUMN_COUNT
	 * @param columnCount  the value for PDSCI.EDC_ELEMENT.COLUMN_COUNT
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public void setColumnCount(String columnCount) {
		this.columnCount = columnCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_ELEMENT.ORDINAL
	 * @return  the value of PDSCI.EDC_ELEMENT.ORDINAL
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public Integer getOrdinal() {
		return ordinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_ELEMENT.ORDINAL
	 * @param ordinal  the value for PDSCI.EDC_ELEMENT.ORDINAL
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public void setOrdinal(Integer ordinal) {
		this.ordinal = ordinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_ELEMENT.PROJ_FLOW
	 * @return  the value of PDSCI.EDC_ELEMENT.PROJ_FLOW
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public String getProjFlow() {
		return projFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_ELEMENT.PROJ_FLOW
	 * @param projFlow  the value for PDSCI.EDC_ELEMENT.PROJ_FLOW
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public void setProjFlow(String projFlow) {
		this.projFlow = projFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_ELEMENT.RECORD_STATUS
	 * @return  the value of PDSCI.EDC_ELEMENT.RECORD_STATUS
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public String getRecordStatus() {
		return recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_ELEMENT.RECORD_STATUS
	 * @param recordStatus  the value for PDSCI.EDC_ELEMENT.RECORD_STATUS
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_ELEMENT.CREATE_TIME
	 * @return  the value of PDSCI.EDC_ELEMENT.CREATE_TIME
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_ELEMENT.CREATE_TIME
	 * @param createTime  the value for PDSCI.EDC_ELEMENT.CREATE_TIME
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_ELEMENT.CREATE_USER_FLOW
	 * @return  the value of PDSCI.EDC_ELEMENT.CREATE_USER_FLOW
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public String getCreateUserFlow() {
		return createUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_ELEMENT.CREATE_USER_FLOW
	 * @param createUserFlow  the value for PDSCI.EDC_ELEMENT.CREATE_USER_FLOW
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public void setCreateUserFlow(String createUserFlow) {
		this.createUserFlow = createUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_ELEMENT.MODIFY_TIME
	 * @return  the value of PDSCI.EDC_ELEMENT.MODIFY_TIME
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public String getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_ELEMENT.MODIFY_TIME
	 * @param modifyTime  the value for PDSCI.EDC_ELEMENT.MODIFY_TIME
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public void setModifyTime(String modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_ELEMENT.MODIFY_USER_FLOW
	 * @return  the value of PDSCI.EDC_ELEMENT.MODIFY_USER_FLOW
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public String getModifyUserFlow() {
		return modifyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_ELEMENT.MODIFY_USER_FLOW
	 * @param modifyUserFlow  the value for PDSCI.EDC_ELEMENT.MODIFY_USER_FLOW
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public void setModifyUserFlow(String modifyUserFlow) {
		this.modifyUserFlow = modifyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_ELEMENT.FIXED_WIDTH
	 * @return  the value of PDSCI.EDC_ELEMENT.FIXED_WIDTH
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public String getFixedWidth() {
		return fixedWidth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_ELEMENT.FIXED_WIDTH
	 * @param fixedWidth  the value for PDSCI.EDC_ELEMENT.FIXED_WIDTH
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public void setFixedWidth(String fixedWidth) {
		this.fixedWidth = fixedWidth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_ELEMENT.IS_VIEW_NAME
	 * @return  the value of PDSCI.EDC_ELEMENT.IS_VIEW_NAME
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public String getIsViewName() {
		return isViewName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_ELEMENT.IS_VIEW_NAME
	 * @param isViewName  the value for PDSCI.EDC_ELEMENT.IS_VIEW_NAME
	 * @mbggenerated  Fri Jul 24 16:54:56 CST 2015
	 */
	public void setIsViewName(String isViewName) {
		this.isViewName = isViewName;
	}
}