package com.pinde.sci.model.mo;

import com.pinde.core.model.MybatisObject;

public class EdcGroup extends MybatisObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_GROUP.GROUP_FLOW
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	private String groupFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_GROUP.GROUP_NAME
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	private String groupName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_GROUP.GROUP_CODE
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	private String groupCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_GROUP.PROPORTION
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	private String proportion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_GROUP.ORDINAL
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	private Integer ordinal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_GROUP.PROJ_FLOW
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	private String projFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_GROUP.RECORD_STATUS
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	private String recordStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_GROUP.CREATE_TIME
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_GROUP.CREATE_USER_FLOW
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	private String createUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_GROUP.MODIFY_TIME
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	private String modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_GROUP.MODIFY_USER_FLOW
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	private String modifyUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EDC_GROUP.GROUP_NOTE
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	private String groupNote;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_GROUP.GROUP_FLOW
	 * @return  the value of PDSCI.EDC_GROUP.GROUP_FLOW
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	public String getGroupFlow() {
		return groupFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_GROUP.GROUP_FLOW
	 * @param groupFlow  the value for PDSCI.EDC_GROUP.GROUP_FLOW
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	public void setGroupFlow(String groupFlow) {
		this.groupFlow = groupFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_GROUP.GROUP_NAME
	 * @return  the value of PDSCI.EDC_GROUP.GROUP_NAME
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	public String getGroupName() {
		return groupName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_GROUP.GROUP_NAME
	 * @param groupName  the value for PDSCI.EDC_GROUP.GROUP_NAME
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_GROUP.GROUP_CODE
	 * @return  the value of PDSCI.EDC_GROUP.GROUP_CODE
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	public String getGroupCode() {
		return groupCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_GROUP.GROUP_CODE
	 * @param groupCode  the value for PDSCI.EDC_GROUP.GROUP_CODE
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	public void setGroupCode(String groupCode) {
		this.groupCode = groupCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_GROUP.PROPORTION
	 * @return  the value of PDSCI.EDC_GROUP.PROPORTION
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	public String getProportion() {
		return proportion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_GROUP.PROPORTION
	 * @param proportion  the value for PDSCI.EDC_GROUP.PROPORTION
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	public void setProportion(String proportion) {
		this.proportion = proportion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_GROUP.ORDINAL
	 * @return  the value of PDSCI.EDC_GROUP.ORDINAL
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	public Integer getOrdinal() {
		return ordinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_GROUP.ORDINAL
	 * @param ordinal  the value for PDSCI.EDC_GROUP.ORDINAL
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	public void setOrdinal(Integer ordinal) {
		this.ordinal = ordinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_GROUP.PROJ_FLOW
	 * @return  the value of PDSCI.EDC_GROUP.PROJ_FLOW
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	public String getProjFlow() {
		return projFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_GROUP.PROJ_FLOW
	 * @param projFlow  the value for PDSCI.EDC_GROUP.PROJ_FLOW
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	public void setProjFlow(String projFlow) {
		this.projFlow = projFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_GROUP.RECORD_STATUS
	 * @return  the value of PDSCI.EDC_GROUP.RECORD_STATUS
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	public String getRecordStatus() {
		return recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_GROUP.RECORD_STATUS
	 * @param recordStatus  the value for PDSCI.EDC_GROUP.RECORD_STATUS
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_GROUP.CREATE_TIME
	 * @return  the value of PDSCI.EDC_GROUP.CREATE_TIME
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_GROUP.CREATE_TIME
	 * @param createTime  the value for PDSCI.EDC_GROUP.CREATE_TIME
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_GROUP.CREATE_USER_FLOW
	 * @return  the value of PDSCI.EDC_GROUP.CREATE_USER_FLOW
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	public String getCreateUserFlow() {
		return createUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_GROUP.CREATE_USER_FLOW
	 * @param createUserFlow  the value for PDSCI.EDC_GROUP.CREATE_USER_FLOW
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	public void setCreateUserFlow(String createUserFlow) {
		this.createUserFlow = createUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_GROUP.MODIFY_TIME
	 * @return  the value of PDSCI.EDC_GROUP.MODIFY_TIME
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	public String getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_GROUP.MODIFY_TIME
	 * @param modifyTime  the value for PDSCI.EDC_GROUP.MODIFY_TIME
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	public void setModifyTime(String modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_GROUP.MODIFY_USER_FLOW
	 * @return  the value of PDSCI.EDC_GROUP.MODIFY_USER_FLOW
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	public String getModifyUserFlow() {
		return modifyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_GROUP.MODIFY_USER_FLOW
	 * @param modifyUserFlow  the value for PDSCI.EDC_GROUP.MODIFY_USER_FLOW
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	public void setModifyUserFlow(String modifyUserFlow) {
		this.modifyUserFlow = modifyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EDC_GROUP.GROUP_NOTE
	 * @return  the value of PDSCI.EDC_GROUP.GROUP_NOTE
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	public String getGroupNote() {
		return groupNote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EDC_GROUP.GROUP_NOTE
	 * @param groupNote  the value for PDSCI.EDC_GROUP.GROUP_NOTE
	 * @mbggenerated  Mon Apr 11 10:46:20 CST 2016
	 */
	public void setGroupNote(String groupNote) {
		this.groupNote = groupNote;
	}
}