package com.pinde.sci.model.mo;

import com.pinde.core.model.MybatisObject;
import java.math.BigDecimal;

public class ErpCrmContractPayBalance extends MybatisObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.RECORD_FLOW
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    private String recordFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.CONTRACT_FLOW
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    private String contractFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.PLAN_FLOW
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    private String planFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.BILL_FLOW
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    private String billFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.PAY_DATE
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    private String payDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.PAY_FUND
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    private BigDecimal payFund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.RECORD_STATUS
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    private String recordStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.CREATE_TIME
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.CREATE_USER_FLOW
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    private String createUserFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.MODIFY_TIME
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.MODIFY_USER_FLOW
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    private String modifyUserFlow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.RECORD_FLOW
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.RECORD_FLOW
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    public String getRecordFlow() {
        return recordFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.RECORD_FLOW
     *
     * @param recordFlow the value for PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.RECORD_FLOW
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    public void setRecordFlow(String recordFlow) {
        this.recordFlow = recordFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.CONTRACT_FLOW
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.CONTRACT_FLOW
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    public String getContractFlow() {
        return contractFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.CONTRACT_FLOW
     *
     * @param contractFlow the value for PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.CONTRACT_FLOW
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    public void setContractFlow(String contractFlow) {
        this.contractFlow = contractFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.PLAN_FLOW
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.PLAN_FLOW
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    public String getPlanFlow() {
        return planFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.PLAN_FLOW
     *
     * @param planFlow the value for PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.PLAN_FLOW
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    public void setPlanFlow(String planFlow) {
        this.planFlow = planFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.BILL_FLOW
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.BILL_FLOW
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    public String getBillFlow() {
        return billFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.BILL_FLOW
     *
     * @param billFlow the value for PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.BILL_FLOW
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    public void setBillFlow(String billFlow) {
        this.billFlow = billFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.PAY_DATE
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.PAY_DATE
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    public String getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.PAY_DATE
     *
     * @param payDate the value for PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.PAY_DATE
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    public void setPayDate(String payDate) {
        this.payDate = payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.PAY_FUND
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.PAY_FUND
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    public BigDecimal getPayFund() {
        return payFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.PAY_FUND
     *
     * @param payFund the value for PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.PAY_FUND
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    public void setPayFund(BigDecimal payFund) {
        this.payFund = payFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.RECORD_STATUS
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.RECORD_STATUS
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    public String getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.RECORD_STATUS
     *
     * @param recordStatus the value for PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.RECORD_STATUS
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.CREATE_TIME
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.CREATE_TIME
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.CREATE_TIME
     *
     * @param createTime the value for PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.CREATE_TIME
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.CREATE_USER_FLOW
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.CREATE_USER_FLOW
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    public String getCreateUserFlow() {
        return createUserFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.CREATE_USER_FLOW
     *
     * @param createUserFlow the value for PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.CREATE_USER_FLOW
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    public void setCreateUserFlow(String createUserFlow) {
        this.createUserFlow = createUserFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.MODIFY_TIME
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.MODIFY_TIME
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.MODIFY_TIME
     *
     * @param modifyTime the value for PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.MODIFY_TIME
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.MODIFY_USER_FLOW
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.MODIFY_USER_FLOW
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    public String getModifyUserFlow() {
        return modifyUserFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.MODIFY_USER_FLOW
     *
     * @param modifyUserFlow the value for PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE.MODIFY_USER_FLOW
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    public void setModifyUserFlow(String modifyUserFlow) {
        this.modifyUserFlow = modifyUserFlow;
    }
}