package com.pinde.sci.model.mo;

import com.pinde.core.model.MybatisObject;

public class ErpCrmContractUserRef extends MybatisObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.RECORD_FLOW
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    private String recordFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.USER_RECORD_FLOW
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    private String userRecordFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.USER_FLOW
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    private String userFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.CONTRACT_FLOW
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    private String contractFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.PRODUCT_FLOW
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    private String productFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.PRODUCT_TYPE_ID
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    private String productTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.PRODUCT_TYPE_NAME
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    private String productTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.USER_CATEGORY_ID
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    private String userCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.USER_CATEGORY_NAME
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    private String userCategoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.RECORD_STATUS
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    private String recordStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.CREATE_TIME
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.CREATE_USER_FLOW
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    private String createUserFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.MODIFY_TIME
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.MODIFY_USER_FLOW
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    private String modifyUserFlow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.RECORD_FLOW
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_USER_REF.RECORD_FLOW
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public String getRecordFlow() {
        return recordFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.RECORD_FLOW
     *
     * @param recordFlow the value for PDSCI.ERP_CRM_CONTRACT_USER_REF.RECORD_FLOW
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public void setRecordFlow(String recordFlow) {
        this.recordFlow = recordFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.USER_RECORD_FLOW
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_USER_REF.USER_RECORD_FLOW
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public String getUserRecordFlow() {
        return userRecordFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.USER_RECORD_FLOW
     *
     * @param userRecordFlow the value for PDSCI.ERP_CRM_CONTRACT_USER_REF.USER_RECORD_FLOW
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public void setUserRecordFlow(String userRecordFlow) {
        this.userRecordFlow = userRecordFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.USER_FLOW
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_USER_REF.USER_FLOW
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public String getUserFlow() {
        return userFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.USER_FLOW
     *
     * @param userFlow the value for PDSCI.ERP_CRM_CONTRACT_USER_REF.USER_FLOW
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public void setUserFlow(String userFlow) {
        this.userFlow = userFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.CONTRACT_FLOW
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_USER_REF.CONTRACT_FLOW
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public String getContractFlow() {
        return contractFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.CONTRACT_FLOW
     *
     * @param contractFlow the value for PDSCI.ERP_CRM_CONTRACT_USER_REF.CONTRACT_FLOW
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public void setContractFlow(String contractFlow) {
        this.contractFlow = contractFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.PRODUCT_FLOW
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_USER_REF.PRODUCT_FLOW
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public String getProductFlow() {
        return productFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.PRODUCT_FLOW
     *
     * @param productFlow the value for PDSCI.ERP_CRM_CONTRACT_USER_REF.PRODUCT_FLOW
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public void setProductFlow(String productFlow) {
        this.productFlow = productFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.PRODUCT_TYPE_ID
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_USER_REF.PRODUCT_TYPE_ID
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public String getProductTypeId() {
        return productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.PRODUCT_TYPE_ID
     *
     * @param productTypeId the value for PDSCI.ERP_CRM_CONTRACT_USER_REF.PRODUCT_TYPE_ID
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public void setProductTypeId(String productTypeId) {
        this.productTypeId = productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.PRODUCT_TYPE_NAME
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_USER_REF.PRODUCT_TYPE_NAME
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public String getProductTypeName() {
        return productTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.PRODUCT_TYPE_NAME
     *
     * @param productTypeName the value for PDSCI.ERP_CRM_CONTRACT_USER_REF.PRODUCT_TYPE_NAME
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public void setProductTypeName(String productTypeName) {
        this.productTypeName = productTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.USER_CATEGORY_ID
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_USER_REF.USER_CATEGORY_ID
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public String getUserCategoryId() {
        return userCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.USER_CATEGORY_ID
     *
     * @param userCategoryId the value for PDSCI.ERP_CRM_CONTRACT_USER_REF.USER_CATEGORY_ID
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public void setUserCategoryId(String userCategoryId) {
        this.userCategoryId = userCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.USER_CATEGORY_NAME
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_USER_REF.USER_CATEGORY_NAME
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public String getUserCategoryName() {
        return userCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.USER_CATEGORY_NAME
     *
     * @param userCategoryName the value for PDSCI.ERP_CRM_CONTRACT_USER_REF.USER_CATEGORY_NAME
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public void setUserCategoryName(String userCategoryName) {
        this.userCategoryName = userCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.RECORD_STATUS
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_USER_REF.RECORD_STATUS
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public String getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.RECORD_STATUS
     *
     * @param recordStatus the value for PDSCI.ERP_CRM_CONTRACT_USER_REF.RECORD_STATUS
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.CREATE_TIME
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_USER_REF.CREATE_TIME
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.CREATE_TIME
     *
     * @param createTime the value for PDSCI.ERP_CRM_CONTRACT_USER_REF.CREATE_TIME
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.CREATE_USER_FLOW
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_USER_REF.CREATE_USER_FLOW
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public String getCreateUserFlow() {
        return createUserFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.CREATE_USER_FLOW
     *
     * @param createUserFlow the value for PDSCI.ERP_CRM_CONTRACT_USER_REF.CREATE_USER_FLOW
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public void setCreateUserFlow(String createUserFlow) {
        this.createUserFlow = createUserFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.MODIFY_TIME
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_USER_REF.MODIFY_TIME
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.MODIFY_TIME
     *
     * @param modifyTime the value for PDSCI.ERP_CRM_CONTRACT_USER_REF.MODIFY_TIME
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.MODIFY_USER_FLOW
     *
     * @return the value of PDSCI.ERP_CRM_CONTRACT_USER_REF.MODIFY_USER_FLOW
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public String getModifyUserFlow() {
        return modifyUserFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.ERP_CRM_CONTRACT_USER_REF.MODIFY_USER_FLOW
     *
     * @param modifyUserFlow the value for PDSCI.ERP_CRM_CONTRACT_USER_REF.MODIFY_USER_FLOW
     *
     * @mbggenerated Sat Feb 28 17:02:45 GMT+08:00 2015
     */
    public void setModifyUserFlow(String modifyUserFlow) {
        this.modifyUserFlow = modifyUserFlow;
    }
}