package com.pinde.sci.model.mo;

import com.pinde.core.model.MybatisObject;

public class ErpOaContactOrder extends MybatisObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String contactFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_NO
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String contactNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.CUSTOMER_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String customerFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.CUSTOMER_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String customerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.CONTRACT_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String contractFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.CONTRACT_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String contractName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_MATTER_ID
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String demandMatterId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_MATTER_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String demandMatterName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.SERVICE_TYPE_ID
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String serviceTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.SERVICE_TYPE_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String serviceTypeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.PRODUCT_TYPE_ID
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String productTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.PRODUCT_TYPE_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String productTypeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.REMARK
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_DATE
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String demandDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_STATUS_ID
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String demandStatusId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_STATUS_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String demandStatusName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.APPLY_DATE
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String applyDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.APPLY_USER_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String applyUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_STATUS_ID
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String contactStatusId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_STATUS_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String contactStatusName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.RECORD_STATUS
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String recordStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.CREATE_TIME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.CREATE_USER_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String createUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.MODIFY_TIME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String modifyUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.APPLY_USER_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String applyUserName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.RECEIVE_DEPT_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String receiveDeptFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.RECEIVE_DEPT_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String receiveDeptName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.COMPLETE_TIME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String completeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.ALIAS_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String aliasName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.APPLY_DEPT_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String applyDeptFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.APPLY_DEPT_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String applyDeptName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.RECEIVE_USER_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String receiveUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.RECEIVE_USER_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String receiveUserName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.CONSUMER_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String consumerFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.CONSUMER_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String consumerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.CONSUMER_ALIAS_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String consumerAliasName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.ORDER_PRODUCT_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String orderProductName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_CONTENT
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	private String contactContent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_FLOW
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getContactFlow() {
		return contactFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_FLOW
	 * @param contactFlow  the value for PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setContactFlow(String contactFlow) {
		this.contactFlow = contactFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_NO
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_NO
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getContactNo() {
		return contactNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_NO
	 * @param contactNo  the value for PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_NO
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CUSTOMER_FLOW
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.CUSTOMER_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getCustomerFlow() {
		return customerFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CUSTOMER_FLOW
	 * @param customerFlow  the value for PDSCI.ERP_OA_CONTACT_ORDER.CUSTOMER_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setCustomerFlow(String customerFlow) {
		this.customerFlow = customerFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CUSTOMER_NAME
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.CUSTOMER_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getCustomerName() {
		return customerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CUSTOMER_NAME
	 * @param customerName  the value for PDSCI.ERP_OA_CONTACT_ORDER.CUSTOMER_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CONTRACT_FLOW
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.CONTRACT_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getContractFlow() {
		return contractFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CONTRACT_FLOW
	 * @param contractFlow  the value for PDSCI.ERP_OA_CONTACT_ORDER.CONTRACT_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setContractFlow(String contractFlow) {
		this.contractFlow = contractFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CONTRACT_NAME
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.CONTRACT_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getContractName() {
		return contractName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CONTRACT_NAME
	 * @param contractName  the value for PDSCI.ERP_OA_CONTACT_ORDER.CONTRACT_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setContractName(String contractName) {
		this.contractName = contractName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_MATTER_ID
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_MATTER_ID
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getDemandMatterId() {
		return demandMatterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_MATTER_ID
	 * @param demandMatterId  the value for PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_MATTER_ID
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setDemandMatterId(String demandMatterId) {
		this.demandMatterId = demandMatterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_MATTER_NAME
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_MATTER_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getDemandMatterName() {
		return demandMatterName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_MATTER_NAME
	 * @param demandMatterName  the value for PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_MATTER_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setDemandMatterName(String demandMatterName) {
		this.demandMatterName = demandMatterName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.SERVICE_TYPE_ID
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.SERVICE_TYPE_ID
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getServiceTypeId() {
		return serviceTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.SERVICE_TYPE_ID
	 * @param serviceTypeId  the value for PDSCI.ERP_OA_CONTACT_ORDER.SERVICE_TYPE_ID
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setServiceTypeId(String serviceTypeId) {
		this.serviceTypeId = serviceTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.SERVICE_TYPE_NAME
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.SERVICE_TYPE_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getServiceTypeName() {
		return serviceTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.SERVICE_TYPE_NAME
	 * @param serviceTypeName  the value for PDSCI.ERP_OA_CONTACT_ORDER.SERVICE_TYPE_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setServiceTypeName(String serviceTypeName) {
		this.serviceTypeName = serviceTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.PRODUCT_TYPE_ID
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.PRODUCT_TYPE_ID
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getProductTypeId() {
		return productTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.PRODUCT_TYPE_ID
	 * @param productTypeId  the value for PDSCI.ERP_OA_CONTACT_ORDER.PRODUCT_TYPE_ID
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setProductTypeId(String productTypeId) {
		this.productTypeId = productTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.PRODUCT_TYPE_NAME
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.PRODUCT_TYPE_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getProductTypeName() {
		return productTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.PRODUCT_TYPE_NAME
	 * @param productTypeName  the value for PDSCI.ERP_OA_CONTACT_ORDER.PRODUCT_TYPE_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setProductTypeName(String productTypeName) {
		this.productTypeName = productTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.REMARK
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.REMARK
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.REMARK
	 * @param remark  the value for PDSCI.ERP_OA_CONTACT_ORDER.REMARK
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_DATE
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_DATE
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getDemandDate() {
		return demandDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_DATE
	 * @param demandDate  the value for PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_DATE
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setDemandDate(String demandDate) {
		this.demandDate = demandDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_STATUS_ID
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_STATUS_ID
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getDemandStatusId() {
		return demandStatusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_STATUS_ID
	 * @param demandStatusId  the value for PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_STATUS_ID
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setDemandStatusId(String demandStatusId) {
		this.demandStatusId = demandStatusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_STATUS_NAME
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_STATUS_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getDemandStatusName() {
		return demandStatusName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_STATUS_NAME
	 * @param demandStatusName  the value for PDSCI.ERP_OA_CONTACT_ORDER.DEMAND_STATUS_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setDemandStatusName(String demandStatusName) {
		this.demandStatusName = demandStatusName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.APPLY_DATE
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.APPLY_DATE
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getApplyDate() {
		return applyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.APPLY_DATE
	 * @param applyDate  the value for PDSCI.ERP_OA_CONTACT_ORDER.APPLY_DATE
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setApplyDate(String applyDate) {
		this.applyDate = applyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.APPLY_USER_FLOW
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.APPLY_USER_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getApplyUserFlow() {
		return applyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.APPLY_USER_FLOW
	 * @param applyUserFlow  the value for PDSCI.ERP_OA_CONTACT_ORDER.APPLY_USER_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setApplyUserFlow(String applyUserFlow) {
		this.applyUserFlow = applyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_STATUS_ID
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_STATUS_ID
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getContactStatusId() {
		return contactStatusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_STATUS_ID
	 * @param contactStatusId  the value for PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_STATUS_ID
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setContactStatusId(String contactStatusId) {
		this.contactStatusId = contactStatusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_STATUS_NAME
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_STATUS_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getContactStatusName() {
		return contactStatusName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_STATUS_NAME
	 * @param contactStatusName  the value for PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_STATUS_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setContactStatusName(String contactStatusName) {
		this.contactStatusName = contactStatusName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.RECORD_STATUS
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.RECORD_STATUS
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getRecordStatus() {
		return recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.RECORD_STATUS
	 * @param recordStatus  the value for PDSCI.ERP_OA_CONTACT_ORDER.RECORD_STATUS
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CREATE_TIME
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.CREATE_TIME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CREATE_TIME
	 * @param createTime  the value for PDSCI.ERP_OA_CONTACT_ORDER.CREATE_TIME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CREATE_USER_FLOW
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.CREATE_USER_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getCreateUserFlow() {
		return createUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CREATE_USER_FLOW
	 * @param createUserFlow  the value for PDSCI.ERP_OA_CONTACT_ORDER.CREATE_USER_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setCreateUserFlow(String createUserFlow) {
		this.createUserFlow = createUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.MODIFY_TIME
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.MODIFY_TIME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.MODIFY_TIME
	 * @param modifyTime  the value for PDSCI.ERP_OA_CONTACT_ORDER.MODIFY_TIME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setModifyTime(String modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.MODIFY_USER_FLOW
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getModifyUserFlow() {
		return modifyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.MODIFY_USER_FLOW
	 * @param modifyUserFlow  the value for PDSCI.ERP_OA_CONTACT_ORDER.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setModifyUserFlow(String modifyUserFlow) {
		this.modifyUserFlow = modifyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.APPLY_USER_NAME
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.APPLY_USER_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getApplyUserName() {
		return applyUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.APPLY_USER_NAME
	 * @param applyUserName  the value for PDSCI.ERP_OA_CONTACT_ORDER.APPLY_USER_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setApplyUserName(String applyUserName) {
		this.applyUserName = applyUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.RECEIVE_DEPT_FLOW
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.RECEIVE_DEPT_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getReceiveDeptFlow() {
		return receiveDeptFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.RECEIVE_DEPT_FLOW
	 * @param receiveDeptFlow  the value for PDSCI.ERP_OA_CONTACT_ORDER.RECEIVE_DEPT_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setReceiveDeptFlow(String receiveDeptFlow) {
		this.receiveDeptFlow = receiveDeptFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.RECEIVE_DEPT_NAME
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.RECEIVE_DEPT_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getReceiveDeptName() {
		return receiveDeptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.RECEIVE_DEPT_NAME
	 * @param receiveDeptName  the value for PDSCI.ERP_OA_CONTACT_ORDER.RECEIVE_DEPT_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setReceiveDeptName(String receiveDeptName) {
		this.receiveDeptName = receiveDeptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.COMPLETE_TIME
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.COMPLETE_TIME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getCompleteTime() {
		return completeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.COMPLETE_TIME
	 * @param completeTime  the value for PDSCI.ERP_OA_CONTACT_ORDER.COMPLETE_TIME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setCompleteTime(String completeTime) {
		this.completeTime = completeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.ALIAS_NAME
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.ALIAS_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getAliasName() {
		return aliasName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.ALIAS_NAME
	 * @param aliasName  the value for PDSCI.ERP_OA_CONTACT_ORDER.ALIAS_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setAliasName(String aliasName) {
		this.aliasName = aliasName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.APPLY_DEPT_FLOW
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.APPLY_DEPT_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getApplyDeptFlow() {
		return applyDeptFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.APPLY_DEPT_FLOW
	 * @param applyDeptFlow  the value for PDSCI.ERP_OA_CONTACT_ORDER.APPLY_DEPT_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setApplyDeptFlow(String applyDeptFlow) {
		this.applyDeptFlow = applyDeptFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.APPLY_DEPT_NAME
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.APPLY_DEPT_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getApplyDeptName() {
		return applyDeptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.APPLY_DEPT_NAME
	 * @param applyDeptName  the value for PDSCI.ERP_OA_CONTACT_ORDER.APPLY_DEPT_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setApplyDeptName(String applyDeptName) {
		this.applyDeptName = applyDeptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.RECEIVE_USER_FLOW
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.RECEIVE_USER_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getReceiveUserFlow() {
		return receiveUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.RECEIVE_USER_FLOW
	 * @param receiveUserFlow  the value for PDSCI.ERP_OA_CONTACT_ORDER.RECEIVE_USER_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setReceiveUserFlow(String receiveUserFlow) {
		this.receiveUserFlow = receiveUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.RECEIVE_USER_NAME
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.RECEIVE_USER_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getReceiveUserName() {
		return receiveUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.RECEIVE_USER_NAME
	 * @param receiveUserName  the value for PDSCI.ERP_OA_CONTACT_ORDER.RECEIVE_USER_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setReceiveUserName(String receiveUserName) {
		this.receiveUserName = receiveUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CONSUMER_FLOW
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.CONSUMER_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getConsumerFlow() {
		return consumerFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CONSUMER_FLOW
	 * @param consumerFlow  the value for PDSCI.ERP_OA_CONTACT_ORDER.CONSUMER_FLOW
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setConsumerFlow(String consumerFlow) {
		this.consumerFlow = consumerFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CONSUMER_NAME
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.CONSUMER_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getConsumerName() {
		return consumerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CONSUMER_NAME
	 * @param consumerName  the value for PDSCI.ERP_OA_CONTACT_ORDER.CONSUMER_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setConsumerName(String consumerName) {
		this.consumerName = consumerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CONSUMER_ALIAS_NAME
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.CONSUMER_ALIAS_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getConsumerAliasName() {
		return consumerAliasName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CONSUMER_ALIAS_NAME
	 * @param consumerAliasName  the value for PDSCI.ERP_OA_CONTACT_ORDER.CONSUMER_ALIAS_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setConsumerAliasName(String consumerAliasName) {
		this.consumerAliasName = consumerAliasName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.ORDER_PRODUCT_NAME
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.ORDER_PRODUCT_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getOrderProductName() {
		return orderProductName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.ORDER_PRODUCT_NAME
	 * @param orderProductName  the value for PDSCI.ERP_OA_CONTACT_ORDER.ORDER_PRODUCT_NAME
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setOrderProductName(String orderProductName) {
		this.orderProductName = orderProductName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_CONTENT
	 * @return  the value of PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_CONTENT
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public String getContactContent() {
		return contactContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_CONTENT
	 * @param contactContent  the value for PDSCI.ERP_OA_CONTACT_ORDER.CONTACT_CONTENT
	 * @mbggenerated  Thu Apr 23 11:48:27 CST 2015
	 */
	public void setContactContent(String contactContent) {
		this.contactContent = contactContent;
	}
}