package com.pinde.sci.model.mo;

import com.pinde.core.model.MybatisObject;

public class ExamBookImpDetail extends MybatisObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_BOOK_IMP_DETAIL.IMP_DETAIL_FLOW
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	private String impDetailFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_BOOK_IMP_DETAIL.BOOK_IMP_FLOW
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	private String bookImpFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_BOOK_IMP_DETAIL.QUESTION_TYPE_ID
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	private String questionTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_BOOK_IMP_DETAIL.QUESTION_TYPE_NAME
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	private String questionTypeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_BOOK_IMP_DETAIL.MEMO
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	private String memo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_BOOK_IMP_DETAIL.QUESTION_NUM
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	private Integer questionNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_BOOK_IMP_DETAIL.RECORD_STATUS
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	private String recordStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_BOOK_IMP_DETAIL.CREATE_TIME
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_BOOK_IMP_DETAIL.CREATE_USER_FLOW
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	private String createUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_BOOK_IMP_DETAIL.MODIFY_TIME
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	private String modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_BOOK_IMP_DETAIL.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	private String modifyUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_BOOK_IMP_DETAIL.BOOK_FLOW
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	private String bookFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_BOOK_IMP_DETAIL.QUESTION_FILE
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	private byte[] questionFile;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.IMP_DETAIL_FLOW
	 * @return  the value of PDSCI.EXAM_BOOK_IMP_DETAIL.IMP_DETAIL_FLOW
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public String getImpDetailFlow() {
		return impDetailFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.IMP_DETAIL_FLOW
	 * @param impDetailFlow  the value for PDSCI.EXAM_BOOK_IMP_DETAIL.IMP_DETAIL_FLOW
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public void setImpDetailFlow(String impDetailFlow) {
		this.impDetailFlow = impDetailFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.BOOK_IMP_FLOW
	 * @return  the value of PDSCI.EXAM_BOOK_IMP_DETAIL.BOOK_IMP_FLOW
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public String getBookImpFlow() {
		return bookImpFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.BOOK_IMP_FLOW
	 * @param bookImpFlow  the value for PDSCI.EXAM_BOOK_IMP_DETAIL.BOOK_IMP_FLOW
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public void setBookImpFlow(String bookImpFlow) {
		this.bookImpFlow = bookImpFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.QUESTION_TYPE_ID
	 * @return  the value of PDSCI.EXAM_BOOK_IMP_DETAIL.QUESTION_TYPE_ID
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public String getQuestionTypeId() {
		return questionTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.QUESTION_TYPE_ID
	 * @param questionTypeId  the value for PDSCI.EXAM_BOOK_IMP_DETAIL.QUESTION_TYPE_ID
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public void setQuestionTypeId(String questionTypeId) {
		this.questionTypeId = questionTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.QUESTION_TYPE_NAME
	 * @return  the value of PDSCI.EXAM_BOOK_IMP_DETAIL.QUESTION_TYPE_NAME
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public String getQuestionTypeName() {
		return questionTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.QUESTION_TYPE_NAME
	 * @param questionTypeName  the value for PDSCI.EXAM_BOOK_IMP_DETAIL.QUESTION_TYPE_NAME
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public void setQuestionTypeName(String questionTypeName) {
		this.questionTypeName = questionTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.MEMO
	 * @return  the value of PDSCI.EXAM_BOOK_IMP_DETAIL.MEMO
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.MEMO
	 * @param memo  the value for PDSCI.EXAM_BOOK_IMP_DETAIL.MEMO
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public void setMemo(String memo) {
		this.memo = memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.QUESTION_NUM
	 * @return  the value of PDSCI.EXAM_BOOK_IMP_DETAIL.QUESTION_NUM
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public Integer getQuestionNum() {
		return questionNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.QUESTION_NUM
	 * @param questionNum  the value for PDSCI.EXAM_BOOK_IMP_DETAIL.QUESTION_NUM
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public void setQuestionNum(Integer questionNum) {
		this.questionNum = questionNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.RECORD_STATUS
	 * @return  the value of PDSCI.EXAM_BOOK_IMP_DETAIL.RECORD_STATUS
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public String getRecordStatus() {
		return recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.RECORD_STATUS
	 * @param recordStatus  the value for PDSCI.EXAM_BOOK_IMP_DETAIL.RECORD_STATUS
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.CREATE_TIME
	 * @return  the value of PDSCI.EXAM_BOOK_IMP_DETAIL.CREATE_TIME
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.CREATE_TIME
	 * @param createTime  the value for PDSCI.EXAM_BOOK_IMP_DETAIL.CREATE_TIME
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.CREATE_USER_FLOW
	 * @return  the value of PDSCI.EXAM_BOOK_IMP_DETAIL.CREATE_USER_FLOW
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public String getCreateUserFlow() {
		return createUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.CREATE_USER_FLOW
	 * @param createUserFlow  the value for PDSCI.EXAM_BOOK_IMP_DETAIL.CREATE_USER_FLOW
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public void setCreateUserFlow(String createUserFlow) {
		this.createUserFlow = createUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.MODIFY_TIME
	 * @return  the value of PDSCI.EXAM_BOOK_IMP_DETAIL.MODIFY_TIME
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public String getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.MODIFY_TIME
	 * @param modifyTime  the value for PDSCI.EXAM_BOOK_IMP_DETAIL.MODIFY_TIME
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public void setModifyTime(String modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.MODIFY_USER_FLOW
	 * @return  the value of PDSCI.EXAM_BOOK_IMP_DETAIL.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public String getModifyUserFlow() {
		return modifyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.MODIFY_USER_FLOW
	 * @param modifyUserFlow  the value for PDSCI.EXAM_BOOK_IMP_DETAIL.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public void setModifyUserFlow(String modifyUserFlow) {
		this.modifyUserFlow = modifyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.BOOK_FLOW
	 * @return  the value of PDSCI.EXAM_BOOK_IMP_DETAIL.BOOK_FLOW
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public String getBookFlow() {
		return bookFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.BOOK_FLOW
	 * @param bookFlow  the value for PDSCI.EXAM_BOOK_IMP_DETAIL.BOOK_FLOW
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public void setBookFlow(String bookFlow) {
		this.bookFlow = bookFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.QUESTION_FILE
	 * @return  the value of PDSCI.EXAM_BOOK_IMP_DETAIL.QUESTION_FILE
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public byte[] getQuestionFile() {
		return questionFile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_BOOK_IMP_DETAIL.QUESTION_FILE
	 * @param questionFile  the value for PDSCI.EXAM_BOOK_IMP_DETAIL.QUESTION_FILE
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	public void setQuestionFile(byte[] questionFile) {
		this.questionFile = questionFile;
	}
}