package com.pinde.sci.model.mo;

import com.pinde.core.model.MybatisObject;

public class ExamQuestionBook extends MybatisObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_QUESTION_BOOK.QUESTION_BOOK_FLOW
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	private String questionBookFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_QUESTION_BOOK.QUESTION_FLOW
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	private String questionFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_QUESTION_BOOK.BOOK_FLOW
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	private String bookFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_QUESTION_BOOK.BOOK_NAME
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	private String bookName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_QUESTION_BOOK.BOOK_MEMO
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	private String bookMemo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_QUESTION_BOOK.SUBJECT_FLOW
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	private String subjectFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_QUESTION_BOOK.SUNJECT_NAME
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	private String sunjectName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_QUESTION_BOOK.SUBJECT_MEMO
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	private String subjectMemo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_QUESTION_BOOK.RECORD_STATUS
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	private String recordStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_QUESTION_BOOK.CREATE_TIME
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_QUESTION_BOOK.CREATE_USER_FLOW
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	private String createUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_QUESTION_BOOK.MODIFY_TIME
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	private String modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_QUESTION_BOOK.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	private String modifyUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.EXAM_QUESTION_BOOK.QUESTION_CODE
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	private String questionCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_QUESTION_BOOK.QUESTION_BOOK_FLOW
	 * @return  the value of PDSCI.EXAM_QUESTION_BOOK.QUESTION_BOOK_FLOW
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public String getQuestionBookFlow() {
		return questionBookFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_QUESTION_BOOK.QUESTION_BOOK_FLOW
	 * @param questionBookFlow  the value for PDSCI.EXAM_QUESTION_BOOK.QUESTION_BOOK_FLOW
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public void setQuestionBookFlow(String questionBookFlow) {
		this.questionBookFlow = questionBookFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_QUESTION_BOOK.QUESTION_FLOW
	 * @return  the value of PDSCI.EXAM_QUESTION_BOOK.QUESTION_FLOW
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public String getQuestionFlow() {
		return questionFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_QUESTION_BOOK.QUESTION_FLOW
	 * @param questionFlow  the value for PDSCI.EXAM_QUESTION_BOOK.QUESTION_FLOW
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public void setQuestionFlow(String questionFlow) {
		this.questionFlow = questionFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_QUESTION_BOOK.BOOK_FLOW
	 * @return  the value of PDSCI.EXAM_QUESTION_BOOK.BOOK_FLOW
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public String getBookFlow() {
		return bookFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_QUESTION_BOOK.BOOK_FLOW
	 * @param bookFlow  the value for PDSCI.EXAM_QUESTION_BOOK.BOOK_FLOW
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public void setBookFlow(String bookFlow) {
		this.bookFlow = bookFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_QUESTION_BOOK.BOOK_NAME
	 * @return  the value of PDSCI.EXAM_QUESTION_BOOK.BOOK_NAME
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public String getBookName() {
		return bookName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_QUESTION_BOOK.BOOK_NAME
	 * @param bookName  the value for PDSCI.EXAM_QUESTION_BOOK.BOOK_NAME
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_QUESTION_BOOK.BOOK_MEMO
	 * @return  the value of PDSCI.EXAM_QUESTION_BOOK.BOOK_MEMO
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public String getBookMemo() {
		return bookMemo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_QUESTION_BOOK.BOOK_MEMO
	 * @param bookMemo  the value for PDSCI.EXAM_QUESTION_BOOK.BOOK_MEMO
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public void setBookMemo(String bookMemo) {
		this.bookMemo = bookMemo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_QUESTION_BOOK.SUBJECT_FLOW
	 * @return  the value of PDSCI.EXAM_QUESTION_BOOK.SUBJECT_FLOW
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public String getSubjectFlow() {
		return subjectFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_QUESTION_BOOK.SUBJECT_FLOW
	 * @param subjectFlow  the value for PDSCI.EXAM_QUESTION_BOOK.SUBJECT_FLOW
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public void setSubjectFlow(String subjectFlow) {
		this.subjectFlow = subjectFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_QUESTION_BOOK.SUNJECT_NAME
	 * @return  the value of PDSCI.EXAM_QUESTION_BOOK.SUNJECT_NAME
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public String getSunjectName() {
		return sunjectName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_QUESTION_BOOK.SUNJECT_NAME
	 * @param sunjectName  the value for PDSCI.EXAM_QUESTION_BOOK.SUNJECT_NAME
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public void setSunjectName(String sunjectName) {
		this.sunjectName = sunjectName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_QUESTION_BOOK.SUBJECT_MEMO
	 * @return  the value of PDSCI.EXAM_QUESTION_BOOK.SUBJECT_MEMO
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public String getSubjectMemo() {
		return subjectMemo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_QUESTION_BOOK.SUBJECT_MEMO
	 * @param subjectMemo  the value for PDSCI.EXAM_QUESTION_BOOK.SUBJECT_MEMO
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public void setSubjectMemo(String subjectMemo) {
		this.subjectMemo = subjectMemo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_QUESTION_BOOK.RECORD_STATUS
	 * @return  the value of PDSCI.EXAM_QUESTION_BOOK.RECORD_STATUS
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public String getRecordStatus() {
		return recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_QUESTION_BOOK.RECORD_STATUS
	 * @param recordStatus  the value for PDSCI.EXAM_QUESTION_BOOK.RECORD_STATUS
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_QUESTION_BOOK.CREATE_TIME
	 * @return  the value of PDSCI.EXAM_QUESTION_BOOK.CREATE_TIME
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_QUESTION_BOOK.CREATE_TIME
	 * @param createTime  the value for PDSCI.EXAM_QUESTION_BOOK.CREATE_TIME
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_QUESTION_BOOK.CREATE_USER_FLOW
	 * @return  the value of PDSCI.EXAM_QUESTION_BOOK.CREATE_USER_FLOW
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public String getCreateUserFlow() {
		return createUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_QUESTION_BOOK.CREATE_USER_FLOW
	 * @param createUserFlow  the value for PDSCI.EXAM_QUESTION_BOOK.CREATE_USER_FLOW
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public void setCreateUserFlow(String createUserFlow) {
		this.createUserFlow = createUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_QUESTION_BOOK.MODIFY_TIME
	 * @return  the value of PDSCI.EXAM_QUESTION_BOOK.MODIFY_TIME
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public String getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_QUESTION_BOOK.MODIFY_TIME
	 * @param modifyTime  the value for PDSCI.EXAM_QUESTION_BOOK.MODIFY_TIME
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public void setModifyTime(String modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_QUESTION_BOOK.MODIFY_USER_FLOW
	 * @return  the value of PDSCI.EXAM_QUESTION_BOOK.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public String getModifyUserFlow() {
		return modifyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_QUESTION_BOOK.MODIFY_USER_FLOW
	 * @param modifyUserFlow  the value for PDSCI.EXAM_QUESTION_BOOK.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public void setModifyUserFlow(String modifyUserFlow) {
		this.modifyUserFlow = modifyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.EXAM_QUESTION_BOOK.QUESTION_CODE
	 * @return  the value of PDSCI.EXAM_QUESTION_BOOK.QUESTION_CODE
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public String getQuestionCode() {
		return questionCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.EXAM_QUESTION_BOOK.QUESTION_CODE
	 * @param questionCode  the value for PDSCI.EXAM_QUESTION_BOOK.QUESTION_CODE
	 * @mbggenerated  Thu Jan 15 11:47:41 CST 2015
	 */
	public void setQuestionCode(String questionCode) {
		this.questionCode = questionCode;
	}
}