package com.pinde.sci.model.mo;

import com.pinde.core.model.MybatisObject;

public class IrbInfo extends MybatisObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.IRB_INFO.RECORD_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String recordFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.IRB_INFO.IRB_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String irbName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.IRB_INFO.IRB_SHORT_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String irbShortName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.IRB_INFO.MEETING_ADDRESS
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String meetingAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.IRB_INFO.CONTACT_USER
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String contactUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.IRB_INFO.CONTACT_PHONE
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String contactPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.IRB_INFO.CONTACT_MOBILE
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String contactMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.IRB_INFO.CONTACT_EMAIL
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String contactEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.IRB_INFO.ORDINAL
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private Integer ordinal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.IRB_INFO.RECORD_STATUS
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String recordStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.IRB_INFO.CREATE_TIME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.IRB_INFO.CREATE_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String createUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.IRB_INFO.MODIFY_TIME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.IRB_INFO.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String modifyUserFlow;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.IRB_INFO.RECORD_FLOW
	 * @return  the value of PDSCI.IRB_INFO.RECORD_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getRecordFlow() {
		return recordFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.IRB_INFO.RECORD_FLOW
	 * @param recordFlow  the value for PDSCI.IRB_INFO.RECORD_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setRecordFlow(String recordFlow) {
		this.recordFlow = recordFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.IRB_INFO.IRB_NAME
	 * @return  the value of PDSCI.IRB_INFO.IRB_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getIrbName() {
		return irbName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.IRB_INFO.IRB_NAME
	 * @param irbName  the value for PDSCI.IRB_INFO.IRB_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setIrbName(String irbName) {
		this.irbName = irbName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.IRB_INFO.IRB_SHORT_NAME
	 * @return  the value of PDSCI.IRB_INFO.IRB_SHORT_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getIrbShortName() {
		return irbShortName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.IRB_INFO.IRB_SHORT_NAME
	 * @param irbShortName  the value for PDSCI.IRB_INFO.IRB_SHORT_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setIrbShortName(String irbShortName) {
		this.irbShortName = irbShortName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.IRB_INFO.MEETING_ADDRESS
	 * @return  the value of PDSCI.IRB_INFO.MEETING_ADDRESS
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getMeetingAddress() {
		return meetingAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.IRB_INFO.MEETING_ADDRESS
	 * @param meetingAddress  the value for PDSCI.IRB_INFO.MEETING_ADDRESS
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setMeetingAddress(String meetingAddress) {
		this.meetingAddress = meetingAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.IRB_INFO.CONTACT_USER
	 * @return  the value of PDSCI.IRB_INFO.CONTACT_USER
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getContactUser() {
		return contactUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.IRB_INFO.CONTACT_USER
	 * @param contactUser  the value for PDSCI.IRB_INFO.CONTACT_USER
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setContactUser(String contactUser) {
		this.contactUser = contactUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.IRB_INFO.CONTACT_PHONE
	 * @return  the value of PDSCI.IRB_INFO.CONTACT_PHONE
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getContactPhone() {
		return contactPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.IRB_INFO.CONTACT_PHONE
	 * @param contactPhone  the value for PDSCI.IRB_INFO.CONTACT_PHONE
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.IRB_INFO.CONTACT_MOBILE
	 * @return  the value of PDSCI.IRB_INFO.CONTACT_MOBILE
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getContactMobile() {
		return contactMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.IRB_INFO.CONTACT_MOBILE
	 * @param contactMobile  the value for PDSCI.IRB_INFO.CONTACT_MOBILE
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setContactMobile(String contactMobile) {
		this.contactMobile = contactMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.IRB_INFO.CONTACT_EMAIL
	 * @return  the value of PDSCI.IRB_INFO.CONTACT_EMAIL
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getContactEmail() {
		return contactEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.IRB_INFO.CONTACT_EMAIL
	 * @param contactEmail  the value for PDSCI.IRB_INFO.CONTACT_EMAIL
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setContactEmail(String contactEmail) {
		this.contactEmail = contactEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.IRB_INFO.ORDINAL
	 * @return  the value of PDSCI.IRB_INFO.ORDINAL
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public Integer getOrdinal() {
		return ordinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.IRB_INFO.ORDINAL
	 * @param ordinal  the value for PDSCI.IRB_INFO.ORDINAL
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setOrdinal(Integer ordinal) {
		this.ordinal = ordinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.IRB_INFO.RECORD_STATUS
	 * @return  the value of PDSCI.IRB_INFO.RECORD_STATUS
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getRecordStatus() {
		return recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.IRB_INFO.RECORD_STATUS
	 * @param recordStatus  the value for PDSCI.IRB_INFO.RECORD_STATUS
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.IRB_INFO.CREATE_TIME
	 * @return  the value of PDSCI.IRB_INFO.CREATE_TIME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.IRB_INFO.CREATE_TIME
	 * @param createTime  the value for PDSCI.IRB_INFO.CREATE_TIME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.IRB_INFO.CREATE_USER_FLOW
	 * @return  the value of PDSCI.IRB_INFO.CREATE_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getCreateUserFlow() {
		return createUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.IRB_INFO.CREATE_USER_FLOW
	 * @param createUserFlow  the value for PDSCI.IRB_INFO.CREATE_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setCreateUserFlow(String createUserFlow) {
		this.createUserFlow = createUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.IRB_INFO.MODIFY_TIME
	 * @return  the value of PDSCI.IRB_INFO.MODIFY_TIME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.IRB_INFO.MODIFY_TIME
	 * @param modifyTime  the value for PDSCI.IRB_INFO.MODIFY_TIME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setModifyTime(String modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.IRB_INFO.MODIFY_USER_FLOW
	 * @return  the value of PDSCI.IRB_INFO.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getModifyUserFlow() {
		return modifyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.IRB_INFO.MODIFY_USER_FLOW
	 * @param modifyUserFlow  the value for PDSCI.IRB_INFO.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setModifyUserFlow(String modifyUserFlow) {
		this.modifyUserFlow = modifyUserFlow;
	}
}