package com.pinde.sci.model.mo;

import com.pinde.core.model.MybatisObject;

public class PubAttribute extends MybatisObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.PUB_ATTRIBUTE.ATTR_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String attrFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.PUB_ATTRIBUTE.ATTR_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String attrName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.PUB_ATTRIBUTE.ATTR_CODE
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String attrCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.PUB_ATTRIBUTE.ATTR_VAR_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String attrVarName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.PUB_ATTRIBUTE.MODULE_CODE
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String moduleCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.PUB_ATTRIBUTE.ELEMENT_CODE
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String elementCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.PUB_ATTRIBUTE.ELEMENT_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String elementName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.PUB_ATTRIBUTE.DATA_TYPE_ID
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String dataTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.PUB_ATTRIBUTE.DATA_TYPE_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String dataTypeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.PUB_ATTRIBUTE.DATA_LENGTH
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String dataLength;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.PUB_ATTRIBUTE.DATA_DECIMAL_LENGTH
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String dataDecimalLength;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.PUB_ATTRIBUTE.INPUT_TYPE_ID
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String inputTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.PUB_ATTRIBUTE.INPUT_TYPE_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String inputTypeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.PUB_ATTRIBUTE.ORDINAL
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private Integer ordinal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.PUB_ATTRIBUTE.IS_VIEW_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String isViewName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.PUB_ATTRIBUTE.RECORD_STATUS
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String recordStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.PUB_ATTRIBUTE.CREATE_TIME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.PUB_ATTRIBUTE.CREATE_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String createUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.PUB_ATTRIBUTE.MODIFY_TIME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.PUB_ATTRIBUTE.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String modifyUserFlow;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.PUB_ATTRIBUTE.ATTR_FLOW
	 * @return  the value of PDSCI.PUB_ATTRIBUTE.ATTR_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getAttrFlow() {
		return attrFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.PUB_ATTRIBUTE.ATTR_FLOW
	 * @param attrFlow  the value for PDSCI.PUB_ATTRIBUTE.ATTR_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setAttrFlow(String attrFlow) {
		this.attrFlow = attrFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.PUB_ATTRIBUTE.ATTR_NAME
	 * @return  the value of PDSCI.PUB_ATTRIBUTE.ATTR_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getAttrName() {
		return attrName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.PUB_ATTRIBUTE.ATTR_NAME
	 * @param attrName  the value for PDSCI.PUB_ATTRIBUTE.ATTR_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setAttrName(String attrName) {
		this.attrName = attrName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.PUB_ATTRIBUTE.ATTR_CODE
	 * @return  the value of PDSCI.PUB_ATTRIBUTE.ATTR_CODE
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getAttrCode() {
		return attrCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.PUB_ATTRIBUTE.ATTR_CODE
	 * @param attrCode  the value for PDSCI.PUB_ATTRIBUTE.ATTR_CODE
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setAttrCode(String attrCode) {
		this.attrCode = attrCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.PUB_ATTRIBUTE.ATTR_VAR_NAME
	 * @return  the value of PDSCI.PUB_ATTRIBUTE.ATTR_VAR_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getAttrVarName() {
		return attrVarName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.PUB_ATTRIBUTE.ATTR_VAR_NAME
	 * @param attrVarName  the value for PDSCI.PUB_ATTRIBUTE.ATTR_VAR_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setAttrVarName(String attrVarName) {
		this.attrVarName = attrVarName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.PUB_ATTRIBUTE.MODULE_CODE
	 * @return  the value of PDSCI.PUB_ATTRIBUTE.MODULE_CODE
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getModuleCode() {
		return moduleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.PUB_ATTRIBUTE.MODULE_CODE
	 * @param moduleCode  the value for PDSCI.PUB_ATTRIBUTE.MODULE_CODE
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setModuleCode(String moduleCode) {
		this.moduleCode = moduleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.PUB_ATTRIBUTE.ELEMENT_CODE
	 * @return  the value of PDSCI.PUB_ATTRIBUTE.ELEMENT_CODE
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getElementCode() {
		return elementCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.PUB_ATTRIBUTE.ELEMENT_CODE
	 * @param elementCode  the value for PDSCI.PUB_ATTRIBUTE.ELEMENT_CODE
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setElementCode(String elementCode) {
		this.elementCode = elementCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.PUB_ATTRIBUTE.ELEMENT_NAME
	 * @return  the value of PDSCI.PUB_ATTRIBUTE.ELEMENT_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getElementName() {
		return elementName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.PUB_ATTRIBUTE.ELEMENT_NAME
	 * @param elementName  the value for PDSCI.PUB_ATTRIBUTE.ELEMENT_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setElementName(String elementName) {
		this.elementName = elementName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.PUB_ATTRIBUTE.DATA_TYPE_ID
	 * @return  the value of PDSCI.PUB_ATTRIBUTE.DATA_TYPE_ID
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getDataTypeId() {
		return dataTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.PUB_ATTRIBUTE.DATA_TYPE_ID
	 * @param dataTypeId  the value for PDSCI.PUB_ATTRIBUTE.DATA_TYPE_ID
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setDataTypeId(String dataTypeId) {
		this.dataTypeId = dataTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.PUB_ATTRIBUTE.DATA_TYPE_NAME
	 * @return  the value of PDSCI.PUB_ATTRIBUTE.DATA_TYPE_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getDataTypeName() {
		return dataTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.PUB_ATTRIBUTE.DATA_TYPE_NAME
	 * @param dataTypeName  the value for PDSCI.PUB_ATTRIBUTE.DATA_TYPE_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setDataTypeName(String dataTypeName) {
		this.dataTypeName = dataTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.PUB_ATTRIBUTE.DATA_LENGTH
	 * @return  the value of PDSCI.PUB_ATTRIBUTE.DATA_LENGTH
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getDataLength() {
		return dataLength;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.PUB_ATTRIBUTE.DATA_LENGTH
	 * @param dataLength  the value for PDSCI.PUB_ATTRIBUTE.DATA_LENGTH
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setDataLength(String dataLength) {
		this.dataLength = dataLength;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.PUB_ATTRIBUTE.DATA_DECIMAL_LENGTH
	 * @return  the value of PDSCI.PUB_ATTRIBUTE.DATA_DECIMAL_LENGTH
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getDataDecimalLength() {
		return dataDecimalLength;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.PUB_ATTRIBUTE.DATA_DECIMAL_LENGTH
	 * @param dataDecimalLength  the value for PDSCI.PUB_ATTRIBUTE.DATA_DECIMAL_LENGTH
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setDataDecimalLength(String dataDecimalLength) {
		this.dataDecimalLength = dataDecimalLength;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.PUB_ATTRIBUTE.INPUT_TYPE_ID
	 * @return  the value of PDSCI.PUB_ATTRIBUTE.INPUT_TYPE_ID
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getInputTypeId() {
		return inputTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.PUB_ATTRIBUTE.INPUT_TYPE_ID
	 * @param inputTypeId  the value for PDSCI.PUB_ATTRIBUTE.INPUT_TYPE_ID
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setInputTypeId(String inputTypeId) {
		this.inputTypeId = inputTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.PUB_ATTRIBUTE.INPUT_TYPE_NAME
	 * @return  the value of PDSCI.PUB_ATTRIBUTE.INPUT_TYPE_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getInputTypeName() {
		return inputTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.PUB_ATTRIBUTE.INPUT_TYPE_NAME
	 * @param inputTypeName  the value for PDSCI.PUB_ATTRIBUTE.INPUT_TYPE_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setInputTypeName(String inputTypeName) {
		this.inputTypeName = inputTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.PUB_ATTRIBUTE.ORDINAL
	 * @return  the value of PDSCI.PUB_ATTRIBUTE.ORDINAL
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public Integer getOrdinal() {
		return ordinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.PUB_ATTRIBUTE.ORDINAL
	 * @param ordinal  the value for PDSCI.PUB_ATTRIBUTE.ORDINAL
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setOrdinal(Integer ordinal) {
		this.ordinal = ordinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.PUB_ATTRIBUTE.IS_VIEW_NAME
	 * @return  the value of PDSCI.PUB_ATTRIBUTE.IS_VIEW_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getIsViewName() {
		return isViewName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.PUB_ATTRIBUTE.IS_VIEW_NAME
	 * @param isViewName  the value for PDSCI.PUB_ATTRIBUTE.IS_VIEW_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setIsViewName(String isViewName) {
		this.isViewName = isViewName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.PUB_ATTRIBUTE.RECORD_STATUS
	 * @return  the value of PDSCI.PUB_ATTRIBUTE.RECORD_STATUS
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getRecordStatus() {
		return recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.PUB_ATTRIBUTE.RECORD_STATUS
	 * @param recordStatus  the value for PDSCI.PUB_ATTRIBUTE.RECORD_STATUS
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.PUB_ATTRIBUTE.CREATE_TIME
	 * @return  the value of PDSCI.PUB_ATTRIBUTE.CREATE_TIME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.PUB_ATTRIBUTE.CREATE_TIME
	 * @param createTime  the value for PDSCI.PUB_ATTRIBUTE.CREATE_TIME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.PUB_ATTRIBUTE.CREATE_USER_FLOW
	 * @return  the value of PDSCI.PUB_ATTRIBUTE.CREATE_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getCreateUserFlow() {
		return createUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.PUB_ATTRIBUTE.CREATE_USER_FLOW
	 * @param createUserFlow  the value for PDSCI.PUB_ATTRIBUTE.CREATE_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setCreateUserFlow(String createUserFlow) {
		this.createUserFlow = createUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.PUB_ATTRIBUTE.MODIFY_TIME
	 * @return  the value of PDSCI.PUB_ATTRIBUTE.MODIFY_TIME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.PUB_ATTRIBUTE.MODIFY_TIME
	 * @param modifyTime  the value for PDSCI.PUB_ATTRIBUTE.MODIFY_TIME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setModifyTime(String modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.PUB_ATTRIBUTE.MODIFY_USER_FLOW
	 * @return  the value of PDSCI.PUB_ATTRIBUTE.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getModifyUserFlow() {
		return modifyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.PUB_ATTRIBUTE.MODIFY_USER_FLOW
	 * @param modifyUserFlow  the value for PDSCI.PUB_ATTRIBUTE.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setModifyUserFlow(String modifyUserFlow) {
		this.modifyUserFlow = modifyUserFlow;
	}
}