package com.pinde.sci.model.mo;

import com.pinde.core.model.MybatisObject;

public class PubTrainSummary extends MybatisObject {
    /**
	 * 
	 */
	private static final long serialVersionUID = 764728285471509016L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.PUB_TRAIN_SUMMARY.RECORD_FLOW
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    private String recordFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.PUB_TRAIN_SUMMARY.SUMMARY_TITLE
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    private String summaryTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.PUB_TRAIN_SUMMARY.SUMMARY_TYPE_ID
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    private String summaryTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.PUB_TRAIN_SUMMARY.SUMMARY_TYPE_NAME
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    private String summaryTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.PUB_TRAIN_SUMMARY.OPER_USER_FLOW
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    private String operUserFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.PUB_TRAIN_SUMMARY.OPER_USER_NAME
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    private String operUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.PUB_TRAIN_SUMMARY.OPER_TIME
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    private String operTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.PUB_TRAIN_SUMMARY.RECORD_STATUS
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    private String recordStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.PUB_TRAIN_SUMMARY.CREATE_TIME
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.PUB_TRAIN_SUMMARY.CREATE_USER_FLOW
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    private String createUserFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.PUB_TRAIN_SUMMARY.MODIFY_TIME
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.PUB_TRAIN_SUMMARY.MODIFY_USER_FLOW
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    private String modifyUserFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDSCI.PUB_TRAIN_SUMMARY.SUMMARY_CONTENT
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    private String summaryContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.PUB_TRAIN_SUMMARY.RECORD_FLOW
     *
     * @return the value of PDSCI.PUB_TRAIN_SUMMARY.RECORD_FLOW
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public String getRecordFlow() {
        return recordFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.PUB_TRAIN_SUMMARY.RECORD_FLOW
     *
     * @param recordFlow the value for PDSCI.PUB_TRAIN_SUMMARY.RECORD_FLOW
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public void setRecordFlow(String recordFlow) {
        this.recordFlow = recordFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.PUB_TRAIN_SUMMARY.SUMMARY_TITLE
     *
     * @return the value of PDSCI.PUB_TRAIN_SUMMARY.SUMMARY_TITLE
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public String getSummaryTitle() {
        return summaryTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.PUB_TRAIN_SUMMARY.SUMMARY_TITLE
     *
     * @param summaryTitle the value for PDSCI.PUB_TRAIN_SUMMARY.SUMMARY_TITLE
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public void setSummaryTitle(String summaryTitle) {
        this.summaryTitle = summaryTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.PUB_TRAIN_SUMMARY.SUMMARY_TYPE_ID
     *
     * @return the value of PDSCI.PUB_TRAIN_SUMMARY.SUMMARY_TYPE_ID
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public String getSummaryTypeId() {
        return summaryTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.PUB_TRAIN_SUMMARY.SUMMARY_TYPE_ID
     *
     * @param summaryTypeId the value for PDSCI.PUB_TRAIN_SUMMARY.SUMMARY_TYPE_ID
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public void setSummaryTypeId(String summaryTypeId) {
        this.summaryTypeId = summaryTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.PUB_TRAIN_SUMMARY.SUMMARY_TYPE_NAME
     *
     * @return the value of PDSCI.PUB_TRAIN_SUMMARY.SUMMARY_TYPE_NAME
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public String getSummaryTypeName() {
        return summaryTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.PUB_TRAIN_SUMMARY.SUMMARY_TYPE_NAME
     *
     * @param summaryTypeName the value for PDSCI.PUB_TRAIN_SUMMARY.SUMMARY_TYPE_NAME
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public void setSummaryTypeName(String summaryTypeName) {
        this.summaryTypeName = summaryTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.PUB_TRAIN_SUMMARY.OPER_USER_FLOW
     *
     * @return the value of PDSCI.PUB_TRAIN_SUMMARY.OPER_USER_FLOW
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public String getOperUserFlow() {
        return operUserFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.PUB_TRAIN_SUMMARY.OPER_USER_FLOW
     *
     * @param operUserFlow the value for PDSCI.PUB_TRAIN_SUMMARY.OPER_USER_FLOW
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public void setOperUserFlow(String operUserFlow) {
        this.operUserFlow = operUserFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.PUB_TRAIN_SUMMARY.OPER_USER_NAME
     *
     * @return the value of PDSCI.PUB_TRAIN_SUMMARY.OPER_USER_NAME
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public String getOperUserName() {
        return operUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.PUB_TRAIN_SUMMARY.OPER_USER_NAME
     *
     * @param operUserName the value for PDSCI.PUB_TRAIN_SUMMARY.OPER_USER_NAME
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public void setOperUserName(String operUserName) {
        this.operUserName = operUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.PUB_TRAIN_SUMMARY.OPER_TIME
     *
     * @return the value of PDSCI.PUB_TRAIN_SUMMARY.OPER_TIME
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public String getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.PUB_TRAIN_SUMMARY.OPER_TIME
     *
     * @param operTime the value for PDSCI.PUB_TRAIN_SUMMARY.OPER_TIME
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public void setOperTime(String operTime) {
        this.operTime = operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.PUB_TRAIN_SUMMARY.RECORD_STATUS
     *
     * @return the value of PDSCI.PUB_TRAIN_SUMMARY.RECORD_STATUS
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public String getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.PUB_TRAIN_SUMMARY.RECORD_STATUS
     *
     * @param recordStatus the value for PDSCI.PUB_TRAIN_SUMMARY.RECORD_STATUS
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.PUB_TRAIN_SUMMARY.CREATE_TIME
     *
     * @return the value of PDSCI.PUB_TRAIN_SUMMARY.CREATE_TIME
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.PUB_TRAIN_SUMMARY.CREATE_TIME
     *
     * @param createTime the value for PDSCI.PUB_TRAIN_SUMMARY.CREATE_TIME
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.PUB_TRAIN_SUMMARY.CREATE_USER_FLOW
     *
     * @return the value of PDSCI.PUB_TRAIN_SUMMARY.CREATE_USER_FLOW
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public String getCreateUserFlow() {
        return createUserFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.PUB_TRAIN_SUMMARY.CREATE_USER_FLOW
     *
     * @param createUserFlow the value for PDSCI.PUB_TRAIN_SUMMARY.CREATE_USER_FLOW
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public void setCreateUserFlow(String createUserFlow) {
        this.createUserFlow = createUserFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.PUB_TRAIN_SUMMARY.MODIFY_TIME
     *
     * @return the value of PDSCI.PUB_TRAIN_SUMMARY.MODIFY_TIME
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.PUB_TRAIN_SUMMARY.MODIFY_TIME
     *
     * @param modifyTime the value for PDSCI.PUB_TRAIN_SUMMARY.MODIFY_TIME
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.PUB_TRAIN_SUMMARY.MODIFY_USER_FLOW
     *
     * @return the value of PDSCI.PUB_TRAIN_SUMMARY.MODIFY_USER_FLOW
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public String getModifyUserFlow() {
        return modifyUserFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.PUB_TRAIN_SUMMARY.MODIFY_USER_FLOW
     *
     * @param modifyUserFlow the value for PDSCI.PUB_TRAIN_SUMMARY.MODIFY_USER_FLOW
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public void setModifyUserFlow(String modifyUserFlow) {
        this.modifyUserFlow = modifyUserFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDSCI.PUB_TRAIN_SUMMARY.SUMMARY_CONTENT
     *
     * @return the value of PDSCI.PUB_TRAIN_SUMMARY.SUMMARY_CONTENT
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public String getSummaryContent() {
        return summaryContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDSCI.PUB_TRAIN_SUMMARY.SUMMARY_CONTENT
     *
     * @param summaryContent the value for PDSCI.PUB_TRAIN_SUMMARY.SUMMARY_CONTENT
     *
     * @mbggenerated Tue Oct 21 10:18:21 CST 2014
     */
    public void setSummaryContent(String summaryContent) {
        this.summaryContent = summaryContent;
    }
}