package com.pinde.sci.model.mo;

public class ResDoctorRecruitWithBLOBs extends ResDoctorRecruit {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.RETEST_NOTICE
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String retestNotice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.ADMIT_NOTICE
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String admitNotice;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.RETEST_NOTICE
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.RETEST_NOTICE
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getRetestNotice() {
		return retestNotice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.RETEST_NOTICE
	 * @param retestNotice  the value for PDSCI.RES_DOCTOR_RECRUIT.RETEST_NOTICE
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setRetestNotice(String retestNotice) {
		this.retestNotice = retestNotice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.ADMIT_NOTICE
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.ADMIT_NOTICE
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getAdmitNotice() {
		return admitNotice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.ADMIT_NOTICE
	 * @param admitNotice  the value for PDSCI.RES_DOCTOR_RECRUIT.ADMIT_NOTICE
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setAdmitNotice(String admitNotice) {
		this.admitNotice = admitNotice;
	}
}