package com.pinde.sci.model.mo;

import com.pinde.core.model.MybatisObject;
import java.math.BigDecimal;

public class ResDoctorRecruit extends MybatisObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_FLOW
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String recruitFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_FLOW
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String doctorFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.ORG_FLOW
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String orgFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.ORG_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String orgName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.SPE_ID
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String speId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.SPE_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String speName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.SWAP_FLAG
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String swapFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_TYPE_ID
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String recruitTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_TYPE_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String recruitTypeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_YEAR
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String recruitYear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.RETEST_FLAG
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String retestFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.EXAM_RESULT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private BigDecimal examResult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.AUDITION_RESULT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private BigDecimal auditionResult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.OPER_RESULT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private BigDecimal operResult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.TOTLE_RESULT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private BigDecimal totleResult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.ADMIT_FLAG
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String admitFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_FLAG
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String recruitFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.CONFIRM_FLAG
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String confirmFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.RECORD_STATUS
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String recordStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.CREATE_TIME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.CREATE_USER_FLOW
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String createUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.MODIFY_TIME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String modifyUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.SWAP_SPE_ID
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String swapSpeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.SWAP_SPE_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String swapSpeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_DATE
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String recruitDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.CAT_SPE_ID
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String catSpeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.CAT_SPE_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String catSpeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.SESSION_NUMBER
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String sessionNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.YET_TRAIN_YEAR
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String yetTrainYear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_STATUS_ID
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String doctorStatusId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_STATUS_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String doctorStatusName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_STRIKE_ID
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String doctorStrikeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_STRIKE_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String doctorStrikeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.TRAIN_NO
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String trainNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.AUDIT_STATUS_ID
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String auditStatusId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.AUDIT_STATUS_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String auditStatusName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.TRAIN_YEAR
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String trainYear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.PLACE_ID
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String placeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.RES_DOCTOR_RECRUIT.PLACE_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	private String placeName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_FLOW
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_FLOW
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getRecruitFlow() {
		return recruitFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_FLOW
	 * @param recruitFlow  the value for PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_FLOW
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setRecruitFlow(String recruitFlow) {
		this.recruitFlow = recruitFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_FLOW
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_FLOW
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getDoctorFlow() {
		return doctorFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_FLOW
	 * @param doctorFlow  the value for PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_FLOW
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setDoctorFlow(String doctorFlow) {
		this.doctorFlow = doctorFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.ORG_FLOW
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.ORG_FLOW
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getOrgFlow() {
		return orgFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.ORG_FLOW
	 * @param orgFlow  the value for PDSCI.RES_DOCTOR_RECRUIT.ORG_FLOW
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setOrgFlow(String orgFlow) {
		this.orgFlow = orgFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.ORG_NAME
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.ORG_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getOrgName() {
		return orgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.ORG_NAME
	 * @param orgName  the value for PDSCI.RES_DOCTOR_RECRUIT.ORG_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.SPE_ID
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.SPE_ID
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getSpeId() {
		return speId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.SPE_ID
	 * @param speId  the value for PDSCI.RES_DOCTOR_RECRUIT.SPE_ID
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setSpeId(String speId) {
		this.speId = speId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.SPE_NAME
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.SPE_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getSpeName() {
		return speName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.SPE_NAME
	 * @param speName  the value for PDSCI.RES_DOCTOR_RECRUIT.SPE_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setSpeName(String speName) {
		this.speName = speName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.SWAP_FLAG
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.SWAP_FLAG
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getSwapFlag() {
		return swapFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.SWAP_FLAG
	 * @param swapFlag  the value for PDSCI.RES_DOCTOR_RECRUIT.SWAP_FLAG
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setSwapFlag(String swapFlag) {
		this.swapFlag = swapFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_TYPE_ID
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_TYPE_ID
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getRecruitTypeId() {
		return recruitTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_TYPE_ID
	 * @param recruitTypeId  the value for PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_TYPE_ID
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setRecruitTypeId(String recruitTypeId) {
		this.recruitTypeId = recruitTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_TYPE_NAME
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_TYPE_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getRecruitTypeName() {
		return recruitTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_TYPE_NAME
	 * @param recruitTypeName  the value for PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_TYPE_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setRecruitTypeName(String recruitTypeName) {
		this.recruitTypeName = recruitTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_YEAR
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_YEAR
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getRecruitYear() {
		return recruitYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_YEAR
	 * @param recruitYear  the value for PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_YEAR
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setRecruitYear(String recruitYear) {
		this.recruitYear = recruitYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.RETEST_FLAG
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.RETEST_FLAG
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getRetestFlag() {
		return retestFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.RETEST_FLAG
	 * @param retestFlag  the value for PDSCI.RES_DOCTOR_RECRUIT.RETEST_FLAG
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setRetestFlag(String retestFlag) {
		this.retestFlag = retestFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.EXAM_RESULT
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.EXAM_RESULT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public BigDecimal getExamResult() {
		return examResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.EXAM_RESULT
	 * @param examResult  the value for PDSCI.RES_DOCTOR_RECRUIT.EXAM_RESULT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setExamResult(BigDecimal examResult) {
		this.examResult = examResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.AUDITION_RESULT
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.AUDITION_RESULT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public BigDecimal getAuditionResult() {
		return auditionResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.AUDITION_RESULT
	 * @param auditionResult  the value for PDSCI.RES_DOCTOR_RECRUIT.AUDITION_RESULT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setAuditionResult(BigDecimal auditionResult) {
		this.auditionResult = auditionResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.OPER_RESULT
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.OPER_RESULT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public BigDecimal getOperResult() {
		return operResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.OPER_RESULT
	 * @param operResult  the value for PDSCI.RES_DOCTOR_RECRUIT.OPER_RESULT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setOperResult(BigDecimal operResult) {
		this.operResult = operResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.TOTLE_RESULT
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.TOTLE_RESULT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public BigDecimal getTotleResult() {
		return totleResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.TOTLE_RESULT
	 * @param totleResult  the value for PDSCI.RES_DOCTOR_RECRUIT.TOTLE_RESULT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setTotleResult(BigDecimal totleResult) {
		this.totleResult = totleResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.ADMIT_FLAG
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.ADMIT_FLAG
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getAdmitFlag() {
		return admitFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.ADMIT_FLAG
	 * @param admitFlag  the value for PDSCI.RES_DOCTOR_RECRUIT.ADMIT_FLAG
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setAdmitFlag(String admitFlag) {
		this.admitFlag = admitFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_FLAG
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_FLAG
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getRecruitFlag() {
		return recruitFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_FLAG
	 * @param recruitFlag  the value for PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_FLAG
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setRecruitFlag(String recruitFlag) {
		this.recruitFlag = recruitFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.CONFIRM_FLAG
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.CONFIRM_FLAG
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getConfirmFlag() {
		return confirmFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.CONFIRM_FLAG
	 * @param confirmFlag  the value for PDSCI.RES_DOCTOR_RECRUIT.CONFIRM_FLAG
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setConfirmFlag(String confirmFlag) {
		this.confirmFlag = confirmFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.RECORD_STATUS
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.RECORD_STATUS
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getRecordStatus() {
		return recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.RECORD_STATUS
	 * @param recordStatus  the value for PDSCI.RES_DOCTOR_RECRUIT.RECORD_STATUS
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.CREATE_TIME
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.CREATE_TIME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.CREATE_TIME
	 * @param createTime  the value for PDSCI.RES_DOCTOR_RECRUIT.CREATE_TIME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.CREATE_USER_FLOW
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.CREATE_USER_FLOW
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getCreateUserFlow() {
		return createUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.CREATE_USER_FLOW
	 * @param createUserFlow  the value for PDSCI.RES_DOCTOR_RECRUIT.CREATE_USER_FLOW
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setCreateUserFlow(String createUserFlow) {
		this.createUserFlow = createUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.MODIFY_TIME
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.MODIFY_TIME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.MODIFY_TIME
	 * @param modifyTime  the value for PDSCI.RES_DOCTOR_RECRUIT.MODIFY_TIME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setModifyTime(String modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.MODIFY_USER_FLOW
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getModifyUserFlow() {
		return modifyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.MODIFY_USER_FLOW
	 * @param modifyUserFlow  the value for PDSCI.RES_DOCTOR_RECRUIT.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setModifyUserFlow(String modifyUserFlow) {
		this.modifyUserFlow = modifyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.SWAP_SPE_ID
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.SWAP_SPE_ID
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getSwapSpeId() {
		return swapSpeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.SWAP_SPE_ID
	 * @param swapSpeId  the value for PDSCI.RES_DOCTOR_RECRUIT.SWAP_SPE_ID
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setSwapSpeId(String swapSpeId) {
		this.swapSpeId = swapSpeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.SWAP_SPE_NAME
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.SWAP_SPE_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getSwapSpeName() {
		return swapSpeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.SWAP_SPE_NAME
	 * @param swapSpeName  the value for PDSCI.RES_DOCTOR_RECRUIT.SWAP_SPE_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setSwapSpeName(String swapSpeName) {
		this.swapSpeName = swapSpeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_DATE
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_DATE
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getRecruitDate() {
		return recruitDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_DATE
	 * @param recruitDate  the value for PDSCI.RES_DOCTOR_RECRUIT.RECRUIT_DATE
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setRecruitDate(String recruitDate) {
		this.recruitDate = recruitDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.CAT_SPE_ID
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.CAT_SPE_ID
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getCatSpeId() {
		return catSpeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.CAT_SPE_ID
	 * @param catSpeId  the value for PDSCI.RES_DOCTOR_RECRUIT.CAT_SPE_ID
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setCatSpeId(String catSpeId) {
		this.catSpeId = catSpeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.CAT_SPE_NAME
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.CAT_SPE_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getCatSpeName() {
		return catSpeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.CAT_SPE_NAME
	 * @param catSpeName  the value for PDSCI.RES_DOCTOR_RECRUIT.CAT_SPE_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setCatSpeName(String catSpeName) {
		this.catSpeName = catSpeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.SESSION_NUMBER
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.SESSION_NUMBER
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getSessionNumber() {
		return sessionNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.SESSION_NUMBER
	 * @param sessionNumber  the value for PDSCI.RES_DOCTOR_RECRUIT.SESSION_NUMBER
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setSessionNumber(String sessionNumber) {
		this.sessionNumber = sessionNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.YET_TRAIN_YEAR
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.YET_TRAIN_YEAR
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getYetTrainYear() {
		return yetTrainYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.YET_TRAIN_YEAR
	 * @param yetTrainYear  the value for PDSCI.RES_DOCTOR_RECRUIT.YET_TRAIN_YEAR
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setYetTrainYear(String yetTrainYear) {
		this.yetTrainYear = yetTrainYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_STATUS_ID
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_STATUS_ID
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getDoctorStatusId() {
		return doctorStatusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_STATUS_ID
	 * @param doctorStatusId  the value for PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_STATUS_ID
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setDoctorStatusId(String doctorStatusId) {
		this.doctorStatusId = doctorStatusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_STATUS_NAME
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_STATUS_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getDoctorStatusName() {
		return doctorStatusName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_STATUS_NAME
	 * @param doctorStatusName  the value for PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_STATUS_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setDoctorStatusName(String doctorStatusName) {
		this.doctorStatusName = doctorStatusName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_STRIKE_ID
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_STRIKE_ID
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getDoctorStrikeId() {
		return doctorStrikeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_STRIKE_ID
	 * @param doctorStrikeId  the value for PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_STRIKE_ID
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setDoctorStrikeId(String doctorStrikeId) {
		this.doctorStrikeId = doctorStrikeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_STRIKE_NAME
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_STRIKE_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getDoctorStrikeName() {
		return doctorStrikeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_STRIKE_NAME
	 * @param doctorStrikeName  the value for PDSCI.RES_DOCTOR_RECRUIT.DOCTOR_STRIKE_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setDoctorStrikeName(String doctorStrikeName) {
		this.doctorStrikeName = doctorStrikeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.TRAIN_NO
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.TRAIN_NO
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getTrainNo() {
		return trainNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.TRAIN_NO
	 * @param trainNo  the value for PDSCI.RES_DOCTOR_RECRUIT.TRAIN_NO
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setTrainNo(String trainNo) {
		this.trainNo = trainNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.AUDIT_STATUS_ID
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.AUDIT_STATUS_ID
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getAuditStatusId() {
		return auditStatusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.AUDIT_STATUS_ID
	 * @param auditStatusId  the value for PDSCI.RES_DOCTOR_RECRUIT.AUDIT_STATUS_ID
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setAuditStatusId(String auditStatusId) {
		this.auditStatusId = auditStatusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.AUDIT_STATUS_NAME
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.AUDIT_STATUS_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getAuditStatusName() {
		return auditStatusName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.AUDIT_STATUS_NAME
	 * @param auditStatusName  the value for PDSCI.RES_DOCTOR_RECRUIT.AUDIT_STATUS_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setAuditStatusName(String auditStatusName) {
		this.auditStatusName = auditStatusName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.TRAIN_YEAR
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.TRAIN_YEAR
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getTrainYear() {
		return trainYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.TRAIN_YEAR
	 * @param trainYear  the value for PDSCI.RES_DOCTOR_RECRUIT.TRAIN_YEAR
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setTrainYear(String trainYear) {
		this.trainYear = trainYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.PLACE_ID
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.PLACE_ID
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getPlaceId() {
		return placeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.PLACE_ID
	 * @param placeId  the value for PDSCI.RES_DOCTOR_RECRUIT.PLACE_ID
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setPlaceId(String placeId) {
		this.placeId = placeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.RES_DOCTOR_RECRUIT.PLACE_NAME
	 * @return  the value of PDSCI.RES_DOCTOR_RECRUIT.PLACE_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public String getPlaceName() {
		return placeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.RES_DOCTOR_RECRUIT.PLACE_NAME
	 * @param placeName  the value for PDSCI.RES_DOCTOR_RECRUIT.PLACE_NAME
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	public void setPlaceName(String placeName) {
		this.placeName = placeName;
	}
}