package com.pinde.sci.model.mo;

import com.pinde.core.model.MybatisObject;

public class SchDoctorAbsence extends MybatisObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.ABSENCE_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String absenceFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.DOCTOR_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String doctorFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.DOCTOR_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String doctorName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.SESSION_NUMBER
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String sessionNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.TRAINING_SPE_ID
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String trainingSpeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.TRAINING_SPE_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String trainingSpeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.START_DATE
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String startDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.END_DATE
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String endDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.INTERVAL_DAY
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String intervalDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.ABSENCE_RESON
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String absenceReson;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.RECORD_STATUS
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String recordStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.CREATE_TIME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.CREATE_USER_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String createUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.MODIFY_TIME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.MODIFY_USER_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String modifyUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.DOCTOR_CATEGORY_ID
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String doctorCategoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.DOCTOR_CATEGORY_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String doctorCategoryName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.SCH_DEPT_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String schDeptFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.SCH_DEPT_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String schDeptName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.TEACHER_AGREE_FLAG
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String teacherAgreeFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.HEAD_AGREE_FLAG
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String headAgreeFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.MANAGER_AGREE_FLAG
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String managerAgreeFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.ORG_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String orgFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.ORG_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String orgName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.TEACHER_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String teacherFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.TEACHER_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String teacherName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.HEAD_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String headFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.HEAD_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String headName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.MANAGER_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String managerFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.MANAGER_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String managerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.REPEAL_ABSENCE
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String repealAbsence;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.REPEAL_ABSENCE_DATE
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String repealAbsenceDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.ABSENCE_TYPE_ID
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String absenceTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.ABSENCE_TYPE_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String absenceTypeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.IS_REGISTER
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String isRegister;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.MAKING_FILE
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String makingFile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.DEPT_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String deptFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SCH_DOCTOR_ABSENCE.DEPT_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	private String deptName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.ABSENCE_FLOW
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.ABSENCE_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getAbsenceFlow() {
		return absenceFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.ABSENCE_FLOW
	 * @param absenceFlow  the value for PDSCI.SCH_DOCTOR_ABSENCE.ABSENCE_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setAbsenceFlow(String absenceFlow) {
		this.absenceFlow = absenceFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.DOCTOR_FLOW
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.DOCTOR_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getDoctorFlow() {
		return doctorFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.DOCTOR_FLOW
	 * @param doctorFlow  the value for PDSCI.SCH_DOCTOR_ABSENCE.DOCTOR_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setDoctorFlow(String doctorFlow) {
		this.doctorFlow = doctorFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.DOCTOR_NAME
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.DOCTOR_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getDoctorName() {
		return doctorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.DOCTOR_NAME
	 * @param doctorName  the value for PDSCI.SCH_DOCTOR_ABSENCE.DOCTOR_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setDoctorName(String doctorName) {
		this.doctorName = doctorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.SESSION_NUMBER
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.SESSION_NUMBER
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getSessionNumber() {
		return sessionNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.SESSION_NUMBER
	 * @param sessionNumber  the value for PDSCI.SCH_DOCTOR_ABSENCE.SESSION_NUMBER
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setSessionNumber(String sessionNumber) {
		this.sessionNumber = sessionNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.TRAINING_SPE_ID
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.TRAINING_SPE_ID
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getTrainingSpeId() {
		return trainingSpeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.TRAINING_SPE_ID
	 * @param trainingSpeId  the value for PDSCI.SCH_DOCTOR_ABSENCE.TRAINING_SPE_ID
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setTrainingSpeId(String trainingSpeId) {
		this.trainingSpeId = trainingSpeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.TRAINING_SPE_NAME
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.TRAINING_SPE_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getTrainingSpeName() {
		return trainingSpeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.TRAINING_SPE_NAME
	 * @param trainingSpeName  the value for PDSCI.SCH_DOCTOR_ABSENCE.TRAINING_SPE_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setTrainingSpeName(String trainingSpeName) {
		this.trainingSpeName = trainingSpeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.START_DATE
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.START_DATE
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.START_DATE
	 * @param startDate  the value for PDSCI.SCH_DOCTOR_ABSENCE.START_DATE
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.END_DATE
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.END_DATE
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.END_DATE
	 * @param endDate  the value for PDSCI.SCH_DOCTOR_ABSENCE.END_DATE
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.INTERVAL_DAY
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.INTERVAL_DAY
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getIntervalDay() {
		return intervalDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.INTERVAL_DAY
	 * @param intervalDay  the value for PDSCI.SCH_DOCTOR_ABSENCE.INTERVAL_DAY
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setIntervalDay(String intervalDay) {
		this.intervalDay = intervalDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.ABSENCE_RESON
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.ABSENCE_RESON
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getAbsenceReson() {
		return absenceReson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.ABSENCE_RESON
	 * @param absenceReson  the value for PDSCI.SCH_DOCTOR_ABSENCE.ABSENCE_RESON
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setAbsenceReson(String absenceReson) {
		this.absenceReson = absenceReson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.RECORD_STATUS
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.RECORD_STATUS
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getRecordStatus() {
		return recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.RECORD_STATUS
	 * @param recordStatus  the value for PDSCI.SCH_DOCTOR_ABSENCE.RECORD_STATUS
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.CREATE_TIME
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.CREATE_TIME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.CREATE_TIME
	 * @param createTime  the value for PDSCI.SCH_DOCTOR_ABSENCE.CREATE_TIME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.CREATE_USER_FLOW
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.CREATE_USER_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getCreateUserFlow() {
		return createUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.CREATE_USER_FLOW
	 * @param createUserFlow  the value for PDSCI.SCH_DOCTOR_ABSENCE.CREATE_USER_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setCreateUserFlow(String createUserFlow) {
		this.createUserFlow = createUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.MODIFY_TIME
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.MODIFY_TIME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.MODIFY_TIME
	 * @param modifyTime  the value for PDSCI.SCH_DOCTOR_ABSENCE.MODIFY_TIME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setModifyTime(String modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.MODIFY_USER_FLOW
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.MODIFY_USER_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getModifyUserFlow() {
		return modifyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.MODIFY_USER_FLOW
	 * @param modifyUserFlow  the value for PDSCI.SCH_DOCTOR_ABSENCE.MODIFY_USER_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setModifyUserFlow(String modifyUserFlow) {
		this.modifyUserFlow = modifyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.DOCTOR_CATEGORY_ID
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.DOCTOR_CATEGORY_ID
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getDoctorCategoryId() {
		return doctorCategoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.DOCTOR_CATEGORY_ID
	 * @param doctorCategoryId  the value for PDSCI.SCH_DOCTOR_ABSENCE.DOCTOR_CATEGORY_ID
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setDoctorCategoryId(String doctorCategoryId) {
		this.doctorCategoryId = doctorCategoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.DOCTOR_CATEGORY_NAME
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.DOCTOR_CATEGORY_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getDoctorCategoryName() {
		return doctorCategoryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.DOCTOR_CATEGORY_NAME
	 * @param doctorCategoryName  the value for PDSCI.SCH_DOCTOR_ABSENCE.DOCTOR_CATEGORY_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setDoctorCategoryName(String doctorCategoryName) {
		this.doctorCategoryName = doctorCategoryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.SCH_DEPT_FLOW
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.SCH_DEPT_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getSchDeptFlow() {
		return schDeptFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.SCH_DEPT_FLOW
	 * @param schDeptFlow  the value for PDSCI.SCH_DOCTOR_ABSENCE.SCH_DEPT_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setSchDeptFlow(String schDeptFlow) {
		this.schDeptFlow = schDeptFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.SCH_DEPT_NAME
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.SCH_DEPT_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getSchDeptName() {
		return schDeptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.SCH_DEPT_NAME
	 * @param schDeptName  the value for PDSCI.SCH_DOCTOR_ABSENCE.SCH_DEPT_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setSchDeptName(String schDeptName) {
		this.schDeptName = schDeptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.TEACHER_AGREE_FLAG
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.TEACHER_AGREE_FLAG
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getTeacherAgreeFlag() {
		return teacherAgreeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.TEACHER_AGREE_FLAG
	 * @param teacherAgreeFlag  the value for PDSCI.SCH_DOCTOR_ABSENCE.TEACHER_AGREE_FLAG
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setTeacherAgreeFlag(String teacherAgreeFlag) {
		this.teacherAgreeFlag = teacherAgreeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.HEAD_AGREE_FLAG
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.HEAD_AGREE_FLAG
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getHeadAgreeFlag() {
		return headAgreeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.HEAD_AGREE_FLAG
	 * @param headAgreeFlag  the value for PDSCI.SCH_DOCTOR_ABSENCE.HEAD_AGREE_FLAG
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setHeadAgreeFlag(String headAgreeFlag) {
		this.headAgreeFlag = headAgreeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.MANAGER_AGREE_FLAG
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.MANAGER_AGREE_FLAG
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getManagerAgreeFlag() {
		return managerAgreeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.MANAGER_AGREE_FLAG
	 * @param managerAgreeFlag  the value for PDSCI.SCH_DOCTOR_ABSENCE.MANAGER_AGREE_FLAG
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setManagerAgreeFlag(String managerAgreeFlag) {
		this.managerAgreeFlag = managerAgreeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.ORG_FLOW
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.ORG_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getOrgFlow() {
		return orgFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.ORG_FLOW
	 * @param orgFlow  the value for PDSCI.SCH_DOCTOR_ABSENCE.ORG_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setOrgFlow(String orgFlow) {
		this.orgFlow = orgFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.ORG_NAME
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.ORG_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getOrgName() {
		return orgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.ORG_NAME
	 * @param orgName  the value for PDSCI.SCH_DOCTOR_ABSENCE.ORG_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.TEACHER_FLOW
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.TEACHER_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getTeacherFlow() {
		return teacherFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.TEACHER_FLOW
	 * @param teacherFlow  the value for PDSCI.SCH_DOCTOR_ABSENCE.TEACHER_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setTeacherFlow(String teacherFlow) {
		this.teacherFlow = teacherFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.TEACHER_NAME
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.TEACHER_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getTeacherName() {
		return teacherName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.TEACHER_NAME
	 * @param teacherName  the value for PDSCI.SCH_DOCTOR_ABSENCE.TEACHER_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.HEAD_FLOW
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.HEAD_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getHeadFlow() {
		return headFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.HEAD_FLOW
	 * @param headFlow  the value for PDSCI.SCH_DOCTOR_ABSENCE.HEAD_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setHeadFlow(String headFlow) {
		this.headFlow = headFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.HEAD_NAME
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.HEAD_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getHeadName() {
		return headName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.HEAD_NAME
	 * @param headName  the value for PDSCI.SCH_DOCTOR_ABSENCE.HEAD_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setHeadName(String headName) {
		this.headName = headName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.MANAGER_FLOW
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.MANAGER_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getManagerFlow() {
		return managerFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.MANAGER_FLOW
	 * @param managerFlow  the value for PDSCI.SCH_DOCTOR_ABSENCE.MANAGER_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setManagerFlow(String managerFlow) {
		this.managerFlow = managerFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.MANAGER_NAME
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.MANAGER_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getManagerName() {
		return managerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.MANAGER_NAME
	 * @param managerName  the value for PDSCI.SCH_DOCTOR_ABSENCE.MANAGER_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setManagerName(String managerName) {
		this.managerName = managerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.REPEAL_ABSENCE
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.REPEAL_ABSENCE
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getRepealAbsence() {
		return repealAbsence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.REPEAL_ABSENCE
	 * @param repealAbsence  the value for PDSCI.SCH_DOCTOR_ABSENCE.REPEAL_ABSENCE
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setRepealAbsence(String repealAbsence) {
		this.repealAbsence = repealAbsence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.REPEAL_ABSENCE_DATE
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.REPEAL_ABSENCE_DATE
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getRepealAbsenceDate() {
		return repealAbsenceDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.REPEAL_ABSENCE_DATE
	 * @param repealAbsenceDate  the value for PDSCI.SCH_DOCTOR_ABSENCE.REPEAL_ABSENCE_DATE
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setRepealAbsenceDate(String repealAbsenceDate) {
		this.repealAbsenceDate = repealAbsenceDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.ABSENCE_TYPE_ID
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.ABSENCE_TYPE_ID
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getAbsenceTypeId() {
		return absenceTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.ABSENCE_TYPE_ID
	 * @param absenceTypeId  the value for PDSCI.SCH_DOCTOR_ABSENCE.ABSENCE_TYPE_ID
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setAbsenceTypeId(String absenceTypeId) {
		this.absenceTypeId = absenceTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.ABSENCE_TYPE_NAME
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.ABSENCE_TYPE_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getAbsenceTypeName() {
		return absenceTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.ABSENCE_TYPE_NAME
	 * @param absenceTypeName  the value for PDSCI.SCH_DOCTOR_ABSENCE.ABSENCE_TYPE_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setAbsenceTypeName(String absenceTypeName) {
		this.absenceTypeName = absenceTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.IS_REGISTER
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.IS_REGISTER
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getIsRegister() {
		return isRegister;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.IS_REGISTER
	 * @param isRegister  the value for PDSCI.SCH_DOCTOR_ABSENCE.IS_REGISTER
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setIsRegister(String isRegister) {
		this.isRegister = isRegister;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.MAKING_FILE
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.MAKING_FILE
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getMakingFile() {
		return makingFile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.MAKING_FILE
	 * @param makingFile  the value for PDSCI.SCH_DOCTOR_ABSENCE.MAKING_FILE
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setMakingFile(String makingFile) {
		this.makingFile = makingFile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.DEPT_FLOW
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.DEPT_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getDeptFlow() {
		return deptFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.DEPT_FLOW
	 * @param deptFlow  the value for PDSCI.SCH_DOCTOR_ABSENCE.DEPT_FLOW
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setDeptFlow(String deptFlow) {
		this.deptFlow = deptFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.DEPT_NAME
	 * @return  the value of PDSCI.SCH_DOCTOR_ABSENCE.DEPT_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public String getDeptName() {
		return deptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SCH_DOCTOR_ABSENCE.DEPT_NAME
	 * @param deptName  the value for PDSCI.SCH_DOCTOR_ABSENCE.DEPT_NAME
	 * @mbggenerated  Fri Aug 21 11:00:50 CST 2015
	 */
	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}
}