package com.pinde.sci.model.mo;

import com.pinde.core.model.MybatisObject;

public class SrmAchReseachrep extends MybatisObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.RESEACHREP_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String reseachrepFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.REP_TITLE
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String repTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.BELONG_ORG_ID
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String belongOrgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.BELONG_ORG_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String belongOrgName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.SUBMIT_ORG
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String submitOrg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.SUBMIT_DATE
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String submitDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.ACCEPT_FLAG
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String acceptFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.SUBJECT_TYPE_ID
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String subjectTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.SUBJECT_TYPE_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String subjectTypeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.ACCEPT_OBJECT_ID
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String acceptObjectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.ACCEPT_OBJECT_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String acceptObjectName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.PROJ_SOURCE_ID
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String projSourceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.PROJ_SOURCE_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String projSourceName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.REP_WORD_COUNT
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String repWordCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.APPLY_ORG_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String applyOrgFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.APPLY_ORG_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String applyOrgName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.REMARK
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.OPER_STATUS_ID
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String operStatusId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.OPER_STATUS_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String operStatusName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.RECORD_STATUS
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String recordStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.CREATE_TIME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.CREATE_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String createUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.MODIFY_TIME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String modifyUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.APPLY_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String applyUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_ACH_RESEACHREP.APPLY_USER_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	private String applyUserName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.RESEACHREP_FLOW
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.RESEACHREP_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getReseachrepFlow() {
		return reseachrepFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.RESEACHREP_FLOW
	 * @param reseachrepFlow  the value for PDSCI.SRM_ACH_RESEACHREP.RESEACHREP_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setReseachrepFlow(String reseachrepFlow) {
		this.reseachrepFlow = reseachrepFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.REP_TITLE
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.REP_TITLE
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getRepTitle() {
		return repTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.REP_TITLE
	 * @param repTitle  the value for PDSCI.SRM_ACH_RESEACHREP.REP_TITLE
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setRepTitle(String repTitle) {
		this.repTitle = repTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.BELONG_ORG_ID
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.BELONG_ORG_ID
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getBelongOrgId() {
		return belongOrgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.BELONG_ORG_ID
	 * @param belongOrgId  the value for PDSCI.SRM_ACH_RESEACHREP.BELONG_ORG_ID
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setBelongOrgId(String belongOrgId) {
		this.belongOrgId = belongOrgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.BELONG_ORG_NAME
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.BELONG_ORG_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getBelongOrgName() {
		return belongOrgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.BELONG_ORG_NAME
	 * @param belongOrgName  the value for PDSCI.SRM_ACH_RESEACHREP.BELONG_ORG_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setBelongOrgName(String belongOrgName) {
		this.belongOrgName = belongOrgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.SUBMIT_ORG
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.SUBMIT_ORG
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getSubmitOrg() {
		return submitOrg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.SUBMIT_ORG
	 * @param submitOrg  the value for PDSCI.SRM_ACH_RESEACHREP.SUBMIT_ORG
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setSubmitOrg(String submitOrg) {
		this.submitOrg = submitOrg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.SUBMIT_DATE
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.SUBMIT_DATE
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getSubmitDate() {
		return submitDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.SUBMIT_DATE
	 * @param submitDate  the value for PDSCI.SRM_ACH_RESEACHREP.SUBMIT_DATE
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setSubmitDate(String submitDate) {
		this.submitDate = submitDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.ACCEPT_FLAG
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.ACCEPT_FLAG
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getAcceptFlag() {
		return acceptFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.ACCEPT_FLAG
	 * @param acceptFlag  the value for PDSCI.SRM_ACH_RESEACHREP.ACCEPT_FLAG
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setAcceptFlag(String acceptFlag) {
		this.acceptFlag = acceptFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.SUBJECT_TYPE_ID
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.SUBJECT_TYPE_ID
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getSubjectTypeId() {
		return subjectTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.SUBJECT_TYPE_ID
	 * @param subjectTypeId  the value for PDSCI.SRM_ACH_RESEACHREP.SUBJECT_TYPE_ID
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setSubjectTypeId(String subjectTypeId) {
		this.subjectTypeId = subjectTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.SUBJECT_TYPE_NAME
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.SUBJECT_TYPE_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getSubjectTypeName() {
		return subjectTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.SUBJECT_TYPE_NAME
	 * @param subjectTypeName  the value for PDSCI.SRM_ACH_RESEACHREP.SUBJECT_TYPE_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setSubjectTypeName(String subjectTypeName) {
		this.subjectTypeName = subjectTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.ACCEPT_OBJECT_ID
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.ACCEPT_OBJECT_ID
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getAcceptObjectId() {
		return acceptObjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.ACCEPT_OBJECT_ID
	 * @param acceptObjectId  the value for PDSCI.SRM_ACH_RESEACHREP.ACCEPT_OBJECT_ID
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setAcceptObjectId(String acceptObjectId) {
		this.acceptObjectId = acceptObjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.ACCEPT_OBJECT_NAME
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.ACCEPT_OBJECT_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getAcceptObjectName() {
		return acceptObjectName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.ACCEPT_OBJECT_NAME
	 * @param acceptObjectName  the value for PDSCI.SRM_ACH_RESEACHREP.ACCEPT_OBJECT_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setAcceptObjectName(String acceptObjectName) {
		this.acceptObjectName = acceptObjectName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.PROJ_SOURCE_ID
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.PROJ_SOURCE_ID
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getProjSourceId() {
		return projSourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.PROJ_SOURCE_ID
	 * @param projSourceId  the value for PDSCI.SRM_ACH_RESEACHREP.PROJ_SOURCE_ID
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setProjSourceId(String projSourceId) {
		this.projSourceId = projSourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.PROJ_SOURCE_NAME
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.PROJ_SOURCE_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getProjSourceName() {
		return projSourceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.PROJ_SOURCE_NAME
	 * @param projSourceName  the value for PDSCI.SRM_ACH_RESEACHREP.PROJ_SOURCE_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setProjSourceName(String projSourceName) {
		this.projSourceName = projSourceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.REP_WORD_COUNT
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.REP_WORD_COUNT
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getRepWordCount() {
		return repWordCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.REP_WORD_COUNT
	 * @param repWordCount  the value for PDSCI.SRM_ACH_RESEACHREP.REP_WORD_COUNT
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setRepWordCount(String repWordCount) {
		this.repWordCount = repWordCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.APPLY_ORG_FLOW
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.APPLY_ORG_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getApplyOrgFlow() {
		return applyOrgFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.APPLY_ORG_FLOW
	 * @param applyOrgFlow  the value for PDSCI.SRM_ACH_RESEACHREP.APPLY_ORG_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setApplyOrgFlow(String applyOrgFlow) {
		this.applyOrgFlow = applyOrgFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.APPLY_ORG_NAME
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.APPLY_ORG_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getApplyOrgName() {
		return applyOrgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.APPLY_ORG_NAME
	 * @param applyOrgName  the value for PDSCI.SRM_ACH_RESEACHREP.APPLY_ORG_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setApplyOrgName(String applyOrgName) {
		this.applyOrgName = applyOrgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.REMARK
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.REMARK
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.REMARK
	 * @param remark  the value for PDSCI.SRM_ACH_RESEACHREP.REMARK
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.OPER_STATUS_ID
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.OPER_STATUS_ID
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getOperStatusId() {
		return operStatusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.OPER_STATUS_ID
	 * @param operStatusId  the value for PDSCI.SRM_ACH_RESEACHREP.OPER_STATUS_ID
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setOperStatusId(String operStatusId) {
		this.operStatusId = operStatusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.OPER_STATUS_NAME
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.OPER_STATUS_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getOperStatusName() {
		return operStatusName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.OPER_STATUS_NAME
	 * @param operStatusName  the value for PDSCI.SRM_ACH_RESEACHREP.OPER_STATUS_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setOperStatusName(String operStatusName) {
		this.operStatusName = operStatusName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.RECORD_STATUS
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.RECORD_STATUS
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getRecordStatus() {
		return recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.RECORD_STATUS
	 * @param recordStatus  the value for PDSCI.SRM_ACH_RESEACHREP.RECORD_STATUS
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.CREATE_TIME
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.CREATE_TIME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.CREATE_TIME
	 * @param createTime  the value for PDSCI.SRM_ACH_RESEACHREP.CREATE_TIME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.CREATE_USER_FLOW
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.CREATE_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getCreateUserFlow() {
		return createUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.CREATE_USER_FLOW
	 * @param createUserFlow  the value for PDSCI.SRM_ACH_RESEACHREP.CREATE_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setCreateUserFlow(String createUserFlow) {
		this.createUserFlow = createUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.MODIFY_TIME
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.MODIFY_TIME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.MODIFY_TIME
	 * @param modifyTime  the value for PDSCI.SRM_ACH_RESEACHREP.MODIFY_TIME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setModifyTime(String modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.MODIFY_USER_FLOW
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getModifyUserFlow() {
		return modifyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.MODIFY_USER_FLOW
	 * @param modifyUserFlow  the value for PDSCI.SRM_ACH_RESEACHREP.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setModifyUserFlow(String modifyUserFlow) {
		this.modifyUserFlow = modifyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.APPLY_USER_FLOW
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.APPLY_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getApplyUserFlow() {
		return applyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.APPLY_USER_FLOW
	 * @param applyUserFlow  the value for PDSCI.SRM_ACH_RESEACHREP.APPLY_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setApplyUserFlow(String applyUserFlow) {
		this.applyUserFlow = applyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_ACH_RESEACHREP.APPLY_USER_NAME
	 * @return  the value of PDSCI.SRM_ACH_RESEACHREP.APPLY_USER_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public String getApplyUserName() {
		return applyUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_ACH_RESEACHREP.APPLY_USER_NAME
	 * @param applyUserName  the value for PDSCI.SRM_ACH_RESEACHREP.APPLY_USER_NAME
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	public void setApplyUserName(String applyUserName) {
		this.applyUserName = applyUserName;
	}
}