package com.pinde.sci.model.mo;

import com.pinde.core.model.MybatisObject;

public class SrmGradeScheme extends MybatisObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_GRADE_SCHEME.SCHEME_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	private String schemeFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_GRADE_SCHEME.SCHEME_NAME
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	private String schemeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_GRADE_SCHEME.PROJ_TYPE_ID
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	private String projTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_GRADE_SCHEME.PROJ_TYPE_NAME
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	private String projTypeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_GRADE_SCHEME.RECORD_STATUS
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	private String recordStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_GRADE_SCHEME.CREATE_TIME
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_GRADE_SCHEME.CREATE_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	private String createUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_GRADE_SCHEME.MODIFY_TIME
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	private String modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_GRADE_SCHEME.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	private String modifyUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_GRADE_SCHEME.EVALUATION_ID
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	private String evaluationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SRM_GRADE_SCHEME.EVALUATION_NAME
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	private String evaluationName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_GRADE_SCHEME.SCHEME_FLOW
	 * @return  the value of PDSCI.SRM_GRADE_SCHEME.SCHEME_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	public String getSchemeFlow() {
		return schemeFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_GRADE_SCHEME.SCHEME_FLOW
	 * @param schemeFlow  the value for PDSCI.SRM_GRADE_SCHEME.SCHEME_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	public void setSchemeFlow(String schemeFlow) {
		this.schemeFlow = schemeFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_GRADE_SCHEME.SCHEME_NAME
	 * @return  the value of PDSCI.SRM_GRADE_SCHEME.SCHEME_NAME
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	public String getSchemeName() {
		return schemeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_GRADE_SCHEME.SCHEME_NAME
	 * @param schemeName  the value for PDSCI.SRM_GRADE_SCHEME.SCHEME_NAME
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	public void setSchemeName(String schemeName) {
		this.schemeName = schemeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_GRADE_SCHEME.PROJ_TYPE_ID
	 * @return  the value of PDSCI.SRM_GRADE_SCHEME.PROJ_TYPE_ID
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	public String getProjTypeId() {
		return projTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_GRADE_SCHEME.PROJ_TYPE_ID
	 * @param projTypeId  the value for PDSCI.SRM_GRADE_SCHEME.PROJ_TYPE_ID
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	public void setProjTypeId(String projTypeId) {
		this.projTypeId = projTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_GRADE_SCHEME.PROJ_TYPE_NAME
	 * @return  the value of PDSCI.SRM_GRADE_SCHEME.PROJ_TYPE_NAME
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	public String getProjTypeName() {
		return projTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_GRADE_SCHEME.PROJ_TYPE_NAME
	 * @param projTypeName  the value for PDSCI.SRM_GRADE_SCHEME.PROJ_TYPE_NAME
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	public void setProjTypeName(String projTypeName) {
		this.projTypeName = projTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_GRADE_SCHEME.RECORD_STATUS
	 * @return  the value of PDSCI.SRM_GRADE_SCHEME.RECORD_STATUS
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	public String getRecordStatus() {
		return recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_GRADE_SCHEME.RECORD_STATUS
	 * @param recordStatus  the value for PDSCI.SRM_GRADE_SCHEME.RECORD_STATUS
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_GRADE_SCHEME.CREATE_TIME
	 * @return  the value of PDSCI.SRM_GRADE_SCHEME.CREATE_TIME
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_GRADE_SCHEME.CREATE_TIME
	 * @param createTime  the value for PDSCI.SRM_GRADE_SCHEME.CREATE_TIME
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_GRADE_SCHEME.CREATE_USER_FLOW
	 * @return  the value of PDSCI.SRM_GRADE_SCHEME.CREATE_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	public String getCreateUserFlow() {
		return createUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_GRADE_SCHEME.CREATE_USER_FLOW
	 * @param createUserFlow  the value for PDSCI.SRM_GRADE_SCHEME.CREATE_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	public void setCreateUserFlow(String createUserFlow) {
		this.createUserFlow = createUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_GRADE_SCHEME.MODIFY_TIME
	 * @return  the value of PDSCI.SRM_GRADE_SCHEME.MODIFY_TIME
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	public String getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_GRADE_SCHEME.MODIFY_TIME
	 * @param modifyTime  the value for PDSCI.SRM_GRADE_SCHEME.MODIFY_TIME
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	public void setModifyTime(String modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_GRADE_SCHEME.MODIFY_USER_FLOW
	 * @return  the value of PDSCI.SRM_GRADE_SCHEME.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	public String getModifyUserFlow() {
		return modifyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_GRADE_SCHEME.MODIFY_USER_FLOW
	 * @param modifyUserFlow  the value for PDSCI.SRM_GRADE_SCHEME.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	public void setModifyUserFlow(String modifyUserFlow) {
		this.modifyUserFlow = modifyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_GRADE_SCHEME.EVALUATION_ID
	 * @return  the value of PDSCI.SRM_GRADE_SCHEME.EVALUATION_ID
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	public String getEvaluationId() {
		return evaluationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_GRADE_SCHEME.EVALUATION_ID
	 * @param evaluationId  the value for PDSCI.SRM_GRADE_SCHEME.EVALUATION_ID
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	public void setEvaluationId(String evaluationId) {
		this.evaluationId = evaluationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SRM_GRADE_SCHEME.EVALUATION_NAME
	 * @return  the value of PDSCI.SRM_GRADE_SCHEME.EVALUATION_NAME
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	public String getEvaluationName() {
		return evaluationName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SRM_GRADE_SCHEME.EVALUATION_NAME
	 * @param evaluationName  the value for PDSCI.SRM_GRADE_SCHEME.EVALUATION_NAME
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	public void setEvaluationName(String evaluationName) {
		this.evaluationName = evaluationName;
	}
}