package com.pinde.sci.model.mo;

import com.pinde.core.model.MybatisObject;

public class SysUser extends MybatisObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.USER_FLOW
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String userFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.USER_CODE
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String userCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.USER_PASSWD
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String userPasswd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.USER_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.SEX_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String sexId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.SEX_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String sexName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.STATUS_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String statusId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.STATUS_DESC
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String statusDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.USER_PHONE
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String userPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.USER_EMAIL
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String userEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.DEPT_FLOW
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String deptFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.DEPT_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String deptName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.ORG_FLOW
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String orgFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.ORG_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String orgName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.ID_NO
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String idNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.USER_BIRTHDAY
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String userBirthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.TITLE_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String titleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.TITLE_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String titleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.DEGREE_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String degreeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.DEGREE_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String degreeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.EDUCATION_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String educationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.EDUCATION_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String educationName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.POST_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String postId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.POST_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String postName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.WEI_XIN_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String weiXinId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.WEI_XIN_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String weiXinName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.WEI_XIN_STATUS_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String weiXinStatusId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.WEI_XIN_STATUS_DESC
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String weiXinStatusDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.SRM_EXPERT_FLAG
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String srmExpertFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.RECORD_STATUS
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String recordStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.CREATE_TIME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.CREATE_USER_FLOW
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String createUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.MODIFY_TIME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String modifyUserFlow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.NATION_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String nationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.NATION_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String nationName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.USER_ADDRESS
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String userAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.USER_EMAIL_STATUS_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String userEmailStatusId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.USER_EMAIL_STATUS_DESC
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String userEmailStatusDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.USER_PHONE_STATUS_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String userPhoneStatusId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.USER_PHONE_STATUS_DESC
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String userPhoneStatusDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.CRET_TYPE_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String cretTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.CRET_TYPE_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String cretTypeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.USER_HEAD_IMG
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String userHeadImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.POLITICS_STATUS_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String politicsStatusId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.POLITICS_STATUS_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String politicsStatusName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.NATIVE_PLACE_PROV_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String nativePlaceProvId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.NATIVE_PLACE_CITY_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String nativePlaceCityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.DOMICILE_PLACE_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String domicilePlaceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.DOMICILE_PLACE_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String domicilePlaceName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.USER_QQ
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String userQq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.MARITAL_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String maritalId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.MARITAL_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String maritalName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.DOMICILE_PLACE_ADDRESS
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String domicilePlaceAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.BEAR_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String bearId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.BEAR_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String bearName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.NATIVE_PLACE_AREA_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String nativePlaceAreaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.NATIVE_PLACE_PROV_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String nativePlaceProvName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.NATIVE_PLACE_CITY_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String nativePlaceCityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PDSCI.SYS_USER.NATIVE_PLACE_AREA_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	private String nativePlaceAreaName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.USER_FLOW
	 * @return  the value of PDSCI.SYS_USER.USER_FLOW
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getUserFlow() {
		return userFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.USER_FLOW
	 * @param userFlow  the value for PDSCI.SYS_USER.USER_FLOW
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setUserFlow(String userFlow) {
		this.userFlow = userFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.USER_CODE
	 * @return  the value of PDSCI.SYS_USER.USER_CODE
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getUserCode() {
		return userCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.USER_CODE
	 * @param userCode  the value for PDSCI.SYS_USER.USER_CODE
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.USER_PASSWD
	 * @return  the value of PDSCI.SYS_USER.USER_PASSWD
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getUserPasswd() {
		return userPasswd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.USER_PASSWD
	 * @param userPasswd  the value for PDSCI.SYS_USER.USER_PASSWD
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setUserPasswd(String userPasswd) {
		this.userPasswd = userPasswd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.USER_NAME
	 * @return  the value of PDSCI.SYS_USER.USER_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.USER_NAME
	 * @param userName  the value for PDSCI.SYS_USER.USER_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.SEX_ID
	 * @return  the value of PDSCI.SYS_USER.SEX_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getSexId() {
		return sexId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.SEX_ID
	 * @param sexId  the value for PDSCI.SYS_USER.SEX_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setSexId(String sexId) {
		this.sexId = sexId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.SEX_NAME
	 * @return  the value of PDSCI.SYS_USER.SEX_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getSexName() {
		return sexName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.SEX_NAME
	 * @param sexName  the value for PDSCI.SYS_USER.SEX_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setSexName(String sexName) {
		this.sexName = sexName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.STATUS_ID
	 * @return  the value of PDSCI.SYS_USER.STATUS_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getStatusId() {
		return statusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.STATUS_ID
	 * @param statusId  the value for PDSCI.SYS_USER.STATUS_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setStatusId(String statusId) {
		this.statusId = statusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.STATUS_DESC
	 * @return  the value of PDSCI.SYS_USER.STATUS_DESC
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getStatusDesc() {
		return statusDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.STATUS_DESC
	 * @param statusDesc  the value for PDSCI.SYS_USER.STATUS_DESC
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setStatusDesc(String statusDesc) {
		this.statusDesc = statusDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.USER_PHONE
	 * @return  the value of PDSCI.SYS_USER.USER_PHONE
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getUserPhone() {
		return userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.USER_PHONE
	 * @param userPhone  the value for PDSCI.SYS_USER.USER_PHONE
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.USER_EMAIL
	 * @return  the value of PDSCI.SYS_USER.USER_EMAIL
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getUserEmail() {
		return userEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.USER_EMAIL
	 * @param userEmail  the value for PDSCI.SYS_USER.USER_EMAIL
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.DEPT_FLOW
	 * @return  the value of PDSCI.SYS_USER.DEPT_FLOW
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getDeptFlow() {
		return deptFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.DEPT_FLOW
	 * @param deptFlow  the value for PDSCI.SYS_USER.DEPT_FLOW
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setDeptFlow(String deptFlow) {
		this.deptFlow = deptFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.DEPT_NAME
	 * @return  the value of PDSCI.SYS_USER.DEPT_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getDeptName() {
		return deptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.DEPT_NAME
	 * @param deptName  the value for PDSCI.SYS_USER.DEPT_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.ORG_FLOW
	 * @return  the value of PDSCI.SYS_USER.ORG_FLOW
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getOrgFlow() {
		return orgFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.ORG_FLOW
	 * @param orgFlow  the value for PDSCI.SYS_USER.ORG_FLOW
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setOrgFlow(String orgFlow) {
		this.orgFlow = orgFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.ORG_NAME
	 * @return  the value of PDSCI.SYS_USER.ORG_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getOrgName() {
		return orgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.ORG_NAME
	 * @param orgName  the value for PDSCI.SYS_USER.ORG_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.ID_NO
	 * @return  the value of PDSCI.SYS_USER.ID_NO
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getIdNo() {
		return idNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.ID_NO
	 * @param idNo  the value for PDSCI.SYS_USER.ID_NO
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setIdNo(String idNo) {
		this.idNo = idNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.USER_BIRTHDAY
	 * @return  the value of PDSCI.SYS_USER.USER_BIRTHDAY
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getUserBirthday() {
		return userBirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.USER_BIRTHDAY
	 * @param userBirthday  the value for PDSCI.SYS_USER.USER_BIRTHDAY
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setUserBirthday(String userBirthday) {
		this.userBirthday = userBirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.TITLE_ID
	 * @return  the value of PDSCI.SYS_USER.TITLE_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getTitleId() {
		return titleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.TITLE_ID
	 * @param titleId  the value for PDSCI.SYS_USER.TITLE_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setTitleId(String titleId) {
		this.titleId = titleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.TITLE_NAME
	 * @return  the value of PDSCI.SYS_USER.TITLE_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getTitleName() {
		return titleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.TITLE_NAME
	 * @param titleName  the value for PDSCI.SYS_USER.TITLE_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setTitleName(String titleName) {
		this.titleName = titleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.DEGREE_ID
	 * @return  the value of PDSCI.SYS_USER.DEGREE_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getDegreeId() {
		return degreeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.DEGREE_ID
	 * @param degreeId  the value for PDSCI.SYS_USER.DEGREE_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setDegreeId(String degreeId) {
		this.degreeId = degreeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.DEGREE_NAME
	 * @return  the value of PDSCI.SYS_USER.DEGREE_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getDegreeName() {
		return degreeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.DEGREE_NAME
	 * @param degreeName  the value for PDSCI.SYS_USER.DEGREE_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setDegreeName(String degreeName) {
		this.degreeName = degreeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.EDUCATION_ID
	 * @return  the value of PDSCI.SYS_USER.EDUCATION_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getEducationId() {
		return educationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.EDUCATION_ID
	 * @param educationId  the value for PDSCI.SYS_USER.EDUCATION_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setEducationId(String educationId) {
		this.educationId = educationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.EDUCATION_NAME
	 * @return  the value of PDSCI.SYS_USER.EDUCATION_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getEducationName() {
		return educationName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.EDUCATION_NAME
	 * @param educationName  the value for PDSCI.SYS_USER.EDUCATION_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setEducationName(String educationName) {
		this.educationName = educationName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.POST_ID
	 * @return  the value of PDSCI.SYS_USER.POST_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getPostId() {
		return postId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.POST_ID
	 * @param postId  the value for PDSCI.SYS_USER.POST_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setPostId(String postId) {
		this.postId = postId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.POST_NAME
	 * @return  the value of PDSCI.SYS_USER.POST_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getPostName() {
		return postName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.POST_NAME
	 * @param postName  the value for PDSCI.SYS_USER.POST_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setPostName(String postName) {
		this.postName = postName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.WEI_XIN_ID
	 * @return  the value of PDSCI.SYS_USER.WEI_XIN_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getWeiXinId() {
		return weiXinId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.WEI_XIN_ID
	 * @param weiXinId  the value for PDSCI.SYS_USER.WEI_XIN_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setWeiXinId(String weiXinId) {
		this.weiXinId = weiXinId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.WEI_XIN_NAME
	 * @return  the value of PDSCI.SYS_USER.WEI_XIN_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getWeiXinName() {
		return weiXinName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.WEI_XIN_NAME
	 * @param weiXinName  the value for PDSCI.SYS_USER.WEI_XIN_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setWeiXinName(String weiXinName) {
		this.weiXinName = weiXinName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.WEI_XIN_STATUS_ID
	 * @return  the value of PDSCI.SYS_USER.WEI_XIN_STATUS_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getWeiXinStatusId() {
		return weiXinStatusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.WEI_XIN_STATUS_ID
	 * @param weiXinStatusId  the value for PDSCI.SYS_USER.WEI_XIN_STATUS_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setWeiXinStatusId(String weiXinStatusId) {
		this.weiXinStatusId = weiXinStatusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.WEI_XIN_STATUS_DESC
	 * @return  the value of PDSCI.SYS_USER.WEI_XIN_STATUS_DESC
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getWeiXinStatusDesc() {
		return weiXinStatusDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.WEI_XIN_STATUS_DESC
	 * @param weiXinStatusDesc  the value for PDSCI.SYS_USER.WEI_XIN_STATUS_DESC
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setWeiXinStatusDesc(String weiXinStatusDesc) {
		this.weiXinStatusDesc = weiXinStatusDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.SRM_EXPERT_FLAG
	 * @return  the value of PDSCI.SYS_USER.SRM_EXPERT_FLAG
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getSrmExpertFlag() {
		return srmExpertFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.SRM_EXPERT_FLAG
	 * @param srmExpertFlag  the value for PDSCI.SYS_USER.SRM_EXPERT_FLAG
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setSrmExpertFlag(String srmExpertFlag) {
		this.srmExpertFlag = srmExpertFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.RECORD_STATUS
	 * @return  the value of PDSCI.SYS_USER.RECORD_STATUS
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getRecordStatus() {
		return recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.RECORD_STATUS
	 * @param recordStatus  the value for PDSCI.SYS_USER.RECORD_STATUS
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.CREATE_TIME
	 * @return  the value of PDSCI.SYS_USER.CREATE_TIME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.CREATE_TIME
	 * @param createTime  the value for PDSCI.SYS_USER.CREATE_TIME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.CREATE_USER_FLOW
	 * @return  the value of PDSCI.SYS_USER.CREATE_USER_FLOW
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getCreateUserFlow() {
		return createUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.CREATE_USER_FLOW
	 * @param createUserFlow  the value for PDSCI.SYS_USER.CREATE_USER_FLOW
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setCreateUserFlow(String createUserFlow) {
		this.createUserFlow = createUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.MODIFY_TIME
	 * @return  the value of PDSCI.SYS_USER.MODIFY_TIME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.MODIFY_TIME
	 * @param modifyTime  the value for PDSCI.SYS_USER.MODIFY_TIME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setModifyTime(String modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.MODIFY_USER_FLOW
	 * @return  the value of PDSCI.SYS_USER.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getModifyUserFlow() {
		return modifyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.MODIFY_USER_FLOW
	 * @param modifyUserFlow  the value for PDSCI.SYS_USER.MODIFY_USER_FLOW
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setModifyUserFlow(String modifyUserFlow) {
		this.modifyUserFlow = modifyUserFlow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.NATION_ID
	 * @return  the value of PDSCI.SYS_USER.NATION_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getNationId() {
		return nationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.NATION_ID
	 * @param nationId  the value for PDSCI.SYS_USER.NATION_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setNationId(String nationId) {
		this.nationId = nationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.NATION_NAME
	 * @return  the value of PDSCI.SYS_USER.NATION_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getNationName() {
		return nationName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.NATION_NAME
	 * @param nationName  the value for PDSCI.SYS_USER.NATION_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setNationName(String nationName) {
		this.nationName = nationName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.USER_ADDRESS
	 * @return  the value of PDSCI.SYS_USER.USER_ADDRESS
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getUserAddress() {
		return userAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.USER_ADDRESS
	 * @param userAddress  the value for PDSCI.SYS_USER.USER_ADDRESS
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.USER_EMAIL_STATUS_ID
	 * @return  the value of PDSCI.SYS_USER.USER_EMAIL_STATUS_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getUserEmailStatusId() {
		return userEmailStatusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.USER_EMAIL_STATUS_ID
	 * @param userEmailStatusId  the value for PDSCI.SYS_USER.USER_EMAIL_STATUS_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setUserEmailStatusId(String userEmailStatusId) {
		this.userEmailStatusId = userEmailStatusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.USER_EMAIL_STATUS_DESC
	 * @return  the value of PDSCI.SYS_USER.USER_EMAIL_STATUS_DESC
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getUserEmailStatusDesc() {
		return userEmailStatusDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.USER_EMAIL_STATUS_DESC
	 * @param userEmailStatusDesc  the value for PDSCI.SYS_USER.USER_EMAIL_STATUS_DESC
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setUserEmailStatusDesc(String userEmailStatusDesc) {
		this.userEmailStatusDesc = userEmailStatusDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.USER_PHONE_STATUS_ID
	 * @return  the value of PDSCI.SYS_USER.USER_PHONE_STATUS_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getUserPhoneStatusId() {
		return userPhoneStatusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.USER_PHONE_STATUS_ID
	 * @param userPhoneStatusId  the value for PDSCI.SYS_USER.USER_PHONE_STATUS_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setUserPhoneStatusId(String userPhoneStatusId) {
		this.userPhoneStatusId = userPhoneStatusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.USER_PHONE_STATUS_DESC
	 * @return  the value of PDSCI.SYS_USER.USER_PHONE_STATUS_DESC
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getUserPhoneStatusDesc() {
		return userPhoneStatusDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.USER_PHONE_STATUS_DESC
	 * @param userPhoneStatusDesc  the value for PDSCI.SYS_USER.USER_PHONE_STATUS_DESC
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setUserPhoneStatusDesc(String userPhoneStatusDesc) {
		this.userPhoneStatusDesc = userPhoneStatusDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.CRET_TYPE_ID
	 * @return  the value of PDSCI.SYS_USER.CRET_TYPE_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getCretTypeId() {
		return cretTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.CRET_TYPE_ID
	 * @param cretTypeId  the value for PDSCI.SYS_USER.CRET_TYPE_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setCretTypeId(String cretTypeId) {
		this.cretTypeId = cretTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.CRET_TYPE_NAME
	 * @return  the value of PDSCI.SYS_USER.CRET_TYPE_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getCretTypeName() {
		return cretTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.CRET_TYPE_NAME
	 * @param cretTypeName  the value for PDSCI.SYS_USER.CRET_TYPE_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setCretTypeName(String cretTypeName) {
		this.cretTypeName = cretTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.USER_HEAD_IMG
	 * @return  the value of PDSCI.SYS_USER.USER_HEAD_IMG
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getUserHeadImg() {
		return userHeadImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.USER_HEAD_IMG
	 * @param userHeadImg  the value for PDSCI.SYS_USER.USER_HEAD_IMG
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setUserHeadImg(String userHeadImg) {
		this.userHeadImg = userHeadImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.POLITICS_STATUS_ID
	 * @return  the value of PDSCI.SYS_USER.POLITICS_STATUS_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getPoliticsStatusId() {
		return politicsStatusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.POLITICS_STATUS_ID
	 * @param politicsStatusId  the value for PDSCI.SYS_USER.POLITICS_STATUS_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setPoliticsStatusId(String politicsStatusId) {
		this.politicsStatusId = politicsStatusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.POLITICS_STATUS_NAME
	 * @return  the value of PDSCI.SYS_USER.POLITICS_STATUS_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getPoliticsStatusName() {
		return politicsStatusName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.POLITICS_STATUS_NAME
	 * @param politicsStatusName  the value for PDSCI.SYS_USER.POLITICS_STATUS_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setPoliticsStatusName(String politicsStatusName) {
		this.politicsStatusName = politicsStatusName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.NATIVE_PLACE_PROV_ID
	 * @return  the value of PDSCI.SYS_USER.NATIVE_PLACE_PROV_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getNativePlaceProvId() {
		return nativePlaceProvId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.NATIVE_PLACE_PROV_ID
	 * @param nativePlaceProvId  the value for PDSCI.SYS_USER.NATIVE_PLACE_PROV_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setNativePlaceProvId(String nativePlaceProvId) {
		this.nativePlaceProvId = nativePlaceProvId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.NATIVE_PLACE_CITY_ID
	 * @return  the value of PDSCI.SYS_USER.NATIVE_PLACE_CITY_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getNativePlaceCityId() {
		return nativePlaceCityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.NATIVE_PLACE_CITY_ID
	 * @param nativePlaceCityId  the value for PDSCI.SYS_USER.NATIVE_PLACE_CITY_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setNativePlaceCityId(String nativePlaceCityId) {
		this.nativePlaceCityId = nativePlaceCityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.DOMICILE_PLACE_ID
	 * @return  the value of PDSCI.SYS_USER.DOMICILE_PLACE_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getDomicilePlaceId() {
		return domicilePlaceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.DOMICILE_PLACE_ID
	 * @param domicilePlaceId  the value for PDSCI.SYS_USER.DOMICILE_PLACE_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setDomicilePlaceId(String domicilePlaceId) {
		this.domicilePlaceId = domicilePlaceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.DOMICILE_PLACE_NAME
	 * @return  the value of PDSCI.SYS_USER.DOMICILE_PLACE_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getDomicilePlaceName() {
		return domicilePlaceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.DOMICILE_PLACE_NAME
	 * @param domicilePlaceName  the value for PDSCI.SYS_USER.DOMICILE_PLACE_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setDomicilePlaceName(String domicilePlaceName) {
		this.domicilePlaceName = domicilePlaceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.USER_QQ
	 * @return  the value of PDSCI.SYS_USER.USER_QQ
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getUserQq() {
		return userQq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.USER_QQ
	 * @param userQq  the value for PDSCI.SYS_USER.USER_QQ
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setUserQq(String userQq) {
		this.userQq = userQq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.MARITAL_ID
	 * @return  the value of PDSCI.SYS_USER.MARITAL_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getMaritalId() {
		return maritalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.MARITAL_ID
	 * @param maritalId  the value for PDSCI.SYS_USER.MARITAL_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setMaritalId(String maritalId) {
		this.maritalId = maritalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.MARITAL_NAME
	 * @return  the value of PDSCI.SYS_USER.MARITAL_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getMaritalName() {
		return maritalName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.MARITAL_NAME
	 * @param maritalName  the value for PDSCI.SYS_USER.MARITAL_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setMaritalName(String maritalName) {
		this.maritalName = maritalName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.DOMICILE_PLACE_ADDRESS
	 * @return  the value of PDSCI.SYS_USER.DOMICILE_PLACE_ADDRESS
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getDomicilePlaceAddress() {
		return domicilePlaceAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.DOMICILE_PLACE_ADDRESS
	 * @param domicilePlaceAddress  the value for PDSCI.SYS_USER.DOMICILE_PLACE_ADDRESS
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setDomicilePlaceAddress(String domicilePlaceAddress) {
		this.domicilePlaceAddress = domicilePlaceAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.BEAR_ID
	 * @return  the value of PDSCI.SYS_USER.BEAR_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getBearId() {
		return bearId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.BEAR_ID
	 * @param bearId  the value for PDSCI.SYS_USER.BEAR_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setBearId(String bearId) {
		this.bearId = bearId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.BEAR_NAME
	 * @return  the value of PDSCI.SYS_USER.BEAR_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getBearName() {
		return bearName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.BEAR_NAME
	 * @param bearName  the value for PDSCI.SYS_USER.BEAR_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setBearName(String bearName) {
		this.bearName = bearName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.NATIVE_PLACE_AREA_ID
	 * @return  the value of PDSCI.SYS_USER.NATIVE_PLACE_AREA_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getNativePlaceAreaId() {
		return nativePlaceAreaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.NATIVE_PLACE_AREA_ID
	 * @param nativePlaceAreaId  the value for PDSCI.SYS_USER.NATIVE_PLACE_AREA_ID
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setNativePlaceAreaId(String nativePlaceAreaId) {
		this.nativePlaceAreaId = nativePlaceAreaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.NATIVE_PLACE_PROV_NAME
	 * @return  the value of PDSCI.SYS_USER.NATIVE_PLACE_PROV_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getNativePlaceProvName() {
		return nativePlaceProvName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.NATIVE_PLACE_PROV_NAME
	 * @param nativePlaceProvName  the value for PDSCI.SYS_USER.NATIVE_PLACE_PROV_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setNativePlaceProvName(String nativePlaceProvName) {
		this.nativePlaceProvName = nativePlaceProvName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.NATIVE_PLACE_CITY_NAME
	 * @return  the value of PDSCI.SYS_USER.NATIVE_PLACE_CITY_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getNativePlaceCityName() {
		return nativePlaceCityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.NATIVE_PLACE_CITY_NAME
	 * @param nativePlaceCityName  the value for PDSCI.SYS_USER.NATIVE_PLACE_CITY_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setNativePlaceCityName(String nativePlaceCityName) {
		this.nativePlaceCityName = nativePlaceCityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PDSCI.SYS_USER.NATIVE_PLACE_AREA_NAME
	 * @return  the value of PDSCI.SYS_USER.NATIVE_PLACE_AREA_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public String getNativePlaceAreaName() {
		return nativePlaceAreaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PDSCI.SYS_USER.NATIVE_PLACE_AREA_NAME
	 * @param nativePlaceAreaName  the value for PDSCI.SYS_USER.NATIVE_PLACE_AREA_NAME
	 * @mbggenerated  Thu Aug 27 15:16:47 CST 2015
	 */
	public void setNativePlaceAreaName(String nativePlaceAreaName) {
		this.nativePlaceAreaName = nativePlaceAreaName;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = -9122411922899008701L;
}