package com.pinde.sci.dao.base;

import com.pinde.sci.model.mo.EdcAttribute;
import com.pinde.sci.model.mo.EdcAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EdcAttributeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDC_ATTRIBUTE
	 * @mbggenerated  Fri Jul 10 15:18:18 CST 2015
	 */
	int countByExample(EdcAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDC_ATTRIBUTE
	 * @mbggenerated  Fri Jul 10 15:18:18 CST 2015
	 */
	int deleteByExample(EdcAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDC_ATTRIBUTE
	 * @mbggenerated  Fri Jul 10 15:18:18 CST 2015
	 */
	int deleteByPrimaryKey(String attrFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDC_ATTRIBUTE
	 * @mbggenerated  Fri Jul 10 15:18:18 CST 2015
	 */
	int insert(EdcAttribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDC_ATTRIBUTE
	 * @mbggenerated  Fri Jul 10 15:18:18 CST 2015
	 */
	int insertSelective(EdcAttribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDC_ATTRIBUTE
	 * @mbggenerated  Fri Jul 10 15:18:18 CST 2015
	 */
	List<EdcAttribute> selectByExample(EdcAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDC_ATTRIBUTE
	 * @mbggenerated  Fri Jul 10 15:18:18 CST 2015
	 */
	EdcAttribute selectByPrimaryKey(String attrFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDC_ATTRIBUTE
	 * @mbggenerated  Fri Jul 10 15:18:18 CST 2015
	 */
	int updateByExampleSelective(@Param("record") EdcAttribute record,
			@Param("example") EdcAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDC_ATTRIBUTE
	 * @mbggenerated  Fri Jul 10 15:18:18 CST 2015
	 */
	int updateByExample(@Param("record") EdcAttribute record,
			@Param("example") EdcAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDC_ATTRIBUTE
	 * @mbggenerated  Fri Jul 10 15:18:18 CST 2015
	 */
	int updateByPrimaryKeySelective(EdcAttribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDC_ATTRIBUTE
	 * @mbggenerated  Fri Jul 10 15:18:18 CST 2015
	 */
	int updateByPrimaryKey(EdcAttribute record);
}