package com.pinde.sci.dao.base;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.pinde.sci.form.edc.ElementSerialSeqForm;
import com.pinde.sci.model.mo.EdcVisitDataEvent;
import com.pinde.sci.model.mo.EdcVisitDataEventExample;

public interface EdcVisitDataEventMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDC_VISIT_DATA_EVENT
	 * @mbggenerated  Fri Apr 29 15:27:31 CST 2016
	 */
	int countByExample(EdcVisitDataEventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDC_VISIT_DATA_EVENT
	 * @mbggenerated  Fri Apr 29 15:27:31 CST 2016
	 */
	int deleteByExample(EdcVisitDataEventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDC_VISIT_DATA_EVENT
	 * @mbggenerated  Fri Apr 29 15:27:31 CST 2016
	 */
	int deleteByPrimaryKey(String recordFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDC_VISIT_DATA_EVENT
	 * @mbggenerated  Fri Apr 29 15:27:31 CST 2016
	 */
	int insert(EdcVisitDataEvent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDC_VISIT_DATA_EVENT
	 * @mbggenerated  Fri Apr 29 15:27:31 CST 2016
	 */
	int insertSelective(EdcVisitDataEvent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDC_VISIT_DATA_EVENT
	 * @mbggenerated  Fri Apr 29 15:27:31 CST 2016
	 */
	List<EdcVisitDataEvent> selectByExample(EdcVisitDataEventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDC_VISIT_DATA_EVENT
	 * @mbggenerated  Fri Apr 29 15:27:31 CST 2016
	 */
	EdcVisitDataEvent selectByPrimaryKey(String recordFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDC_VISIT_DATA_EVENT
	 * @mbggenerated  Fri Apr 29 15:27:31 CST 2016
	 */
	int updateByExampleSelective(@Param("record") EdcVisitDataEvent record,
			@Param("example") EdcVisitDataEventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDC_VISIT_DATA_EVENT
	 * @mbggenerated  Fri Apr 29 15:27:31 CST 2016
	 */
	int updateByExample(@Param("record") EdcVisitDataEvent record,
			@Param("example") EdcVisitDataEventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDC_VISIT_DATA_EVENT
	 * @mbggenerated  Fri Apr 29 15:27:31 CST 2016
	 */
	int updateByPrimaryKeySelective(EdcVisitDataEvent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDC_VISIT_DATA_EVENT
	 * @mbggenerated  Fri Apr 29 15:27:31 CST 2016
	 */
	int updateByPrimaryKey(EdcVisitDataEvent record);
	
}