package com.pinde.sci.dao.base;

import com.pinde.sci.model.mo.EduCourseScoreRef;
import com.pinde.sci.model.mo.EduCourseScoreRefExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EduCourseScoreRefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDSCI.EDU_COURSE_SCORE_REF
     *
     * @mbggenerated Tue Apr 28 13:48:42 GMT+08:00 2015
     */
    int countByExample(EduCourseScoreRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDSCI.EDU_COURSE_SCORE_REF
     *
     * @mbggenerated Tue Apr 28 13:48:42 GMT+08:00 2015
     */
    int deleteByExample(EduCourseScoreRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDSCI.EDU_COURSE_SCORE_REF
     *
     * @mbggenerated Tue Apr 28 13:48:42 GMT+08:00 2015
     */
    int deleteByPrimaryKey(String recordFlow);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDSCI.EDU_COURSE_SCORE_REF
     *
     * @mbggenerated Tue Apr 28 13:48:42 GMT+08:00 2015
     */
    int insert(EduCourseScoreRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDSCI.EDU_COURSE_SCORE_REF
     *
     * @mbggenerated Tue Apr 28 13:48:42 GMT+08:00 2015
     */
    int insertSelective(EduCourseScoreRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDSCI.EDU_COURSE_SCORE_REF
     *
     * @mbggenerated Tue Apr 28 13:48:42 GMT+08:00 2015
     */
    List<EduCourseScoreRef> selectByExample(EduCourseScoreRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDSCI.EDU_COURSE_SCORE_REF
     *
     * @mbggenerated Tue Apr 28 13:48:42 GMT+08:00 2015
     */
    EduCourseScoreRef selectByPrimaryKey(String recordFlow);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDSCI.EDU_COURSE_SCORE_REF
     *
     * @mbggenerated Tue Apr 28 13:48:42 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") EduCourseScoreRef record, @Param("example") EduCourseScoreRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDSCI.EDU_COURSE_SCORE_REF
     *
     * @mbggenerated Tue Apr 28 13:48:42 GMT+08:00 2015
     */
    int updateByExample(@Param("record") EduCourseScoreRef record, @Param("example") EduCourseScoreRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDSCI.EDU_COURSE_SCORE_REF
     *
     * @mbggenerated Tue Apr 28 13:48:42 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(EduCourseScoreRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDSCI.EDU_COURSE_SCORE_REF
     *
     * @mbggenerated Tue Apr 28 13:48:42 GMT+08:00 2015
     */
    int updateByPrimaryKey(EduCourseScoreRef record);
}