package com.pinde.sci.dao.base;

import com.pinde.sci.model.mo.EduUser;
import com.pinde.sci.model.mo.EduUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EduUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDU_USER
	 * @mbggenerated  Thu Aug 20 11:26:00 CST 2015
	 */
	int countByExample(EduUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDU_USER
	 * @mbggenerated  Thu Aug 20 11:26:00 CST 2015
	 */
	int deleteByExample(EduUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDU_USER
	 * @mbggenerated  Thu Aug 20 11:26:00 CST 2015
	 */
	int deleteByPrimaryKey(String userFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDU_USER
	 * @mbggenerated  Thu Aug 20 11:26:00 CST 2015
	 */
	int insert(EduUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDU_USER
	 * @mbggenerated  Thu Aug 20 11:26:00 CST 2015
	 */
	int insertSelective(EduUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDU_USER
	 * @mbggenerated  Thu Aug 20 11:26:00 CST 2015
	 */
	List<EduUser> selectByExampleWithBLOBs(EduUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDU_USER
	 * @mbggenerated  Thu Aug 20 11:26:00 CST 2015
	 */
	List<EduUser> selectByExample(EduUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDU_USER
	 * @mbggenerated  Thu Aug 20 11:26:00 CST 2015
	 */
	EduUser selectByPrimaryKey(String userFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDU_USER
	 * @mbggenerated  Thu Aug 20 11:26:00 CST 2015
	 */
	int updateByExampleSelective(@Param("record") EduUser record,
			@Param("example") EduUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDU_USER
	 * @mbggenerated  Thu Aug 20 11:26:00 CST 2015
	 */
	int updateByExampleWithBLOBs(@Param("record") EduUser record,
			@Param("example") EduUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDU_USER
	 * @mbggenerated  Thu Aug 20 11:26:00 CST 2015
	 */
	int updateByExample(@Param("record") EduUser record,
			@Param("example") EduUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDU_USER
	 * @mbggenerated  Thu Aug 20 11:26:00 CST 2015
	 */
	int updateByPrimaryKeySelective(EduUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDU_USER
	 * @mbggenerated  Thu Aug 20 11:26:00 CST 2015
	 */
	int updateByPrimaryKeyWithBLOBs(EduUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EDU_USER
	 * @mbggenerated  Thu Aug 20 11:26:00 CST 2015
	 */
	int updateByPrimaryKey(EduUser record);
}