package com.pinde.sci.dao.base;

import com.pinde.sci.model.mo.ErpCrmContractPayBalance;
import com.pinde.sci.model.mo.ErpCrmContractPayBalanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ErpCrmContractPayBalanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    int countByExample(ErpCrmContractPayBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    int deleteByExample(ErpCrmContractPayBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    int deleteByPrimaryKey(String recordFlow);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    int insert(ErpCrmContractPayBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    int insertSelective(ErpCrmContractPayBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    List<ErpCrmContractPayBalance> selectByExample(ErpCrmContractPayBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    ErpCrmContractPayBalance selectByPrimaryKey(String recordFlow);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") ErpCrmContractPayBalance record, @Param("example") ErpCrmContractPayBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    int updateByExample(@Param("record") ErpCrmContractPayBalance record, @Param("example") ErpCrmContractPayBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(ErpCrmContractPayBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDSCI.ERP_CRM_CONTRACT_PAY_BALANCE
     *
     * @mbggenerated Fri Feb 27 15:37:31 GMT+08:00 2015
     */
    int updateByPrimaryKey(ErpCrmContractPayBalance record);
}