package com.pinde.sci.dao.base;

import com.pinde.sci.model.mo.ExamBookImpDetail;
import com.pinde.sci.model.mo.ExamBookImpDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExamBookImpDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EXAM_BOOK_IMP_DETAIL
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	int countByExample(ExamBookImpDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EXAM_BOOK_IMP_DETAIL
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	int deleteByExample(ExamBookImpDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EXAM_BOOK_IMP_DETAIL
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	int deleteByPrimaryKey(String impDetailFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EXAM_BOOK_IMP_DETAIL
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	int insert(ExamBookImpDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EXAM_BOOK_IMP_DETAIL
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	int insertSelective(ExamBookImpDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EXAM_BOOK_IMP_DETAIL
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	List<ExamBookImpDetail> selectByExampleWithBLOBs(
			ExamBookImpDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EXAM_BOOK_IMP_DETAIL
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	List<ExamBookImpDetail> selectByExample(ExamBookImpDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EXAM_BOOK_IMP_DETAIL
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	ExamBookImpDetail selectByPrimaryKey(String impDetailFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EXAM_BOOK_IMP_DETAIL
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	int updateByExampleSelective(@Param("record") ExamBookImpDetail record,
			@Param("example") ExamBookImpDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EXAM_BOOK_IMP_DETAIL
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	int updateByExampleWithBLOBs(@Param("record") ExamBookImpDetail record,
			@Param("example") ExamBookImpDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EXAM_BOOK_IMP_DETAIL
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	int updateByExample(@Param("record") ExamBookImpDetail record,
			@Param("example") ExamBookImpDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EXAM_BOOK_IMP_DETAIL
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	int updateByPrimaryKeySelective(ExamBookImpDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EXAM_BOOK_IMP_DETAIL
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	int updateByPrimaryKeyWithBLOBs(ExamBookImpDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.EXAM_BOOK_IMP_DETAIL
	 * @mbggenerated  Thu Jan 22 10:16:46 CST 2015
	 */
	int updateByPrimaryKey(ExamBookImpDetail record);
}