package com.pinde.sci.dao.base;

import com.pinde.sci.model.mo.FstuCredit;
import com.pinde.sci.model.mo.FstuCreditExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FstuCreditMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.FSTU_CREDIT
	 * @mbggenerated  Mon Jun 29 16:58:22 CST 2015
	 */
	int countByExample(FstuCreditExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.FSTU_CREDIT
	 * @mbggenerated  Mon Jun 29 16:58:22 CST 2015
	 */
	int deleteByExample(FstuCreditExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.FSTU_CREDIT
	 * @mbggenerated  Mon Jun 29 16:58:22 CST 2015
	 */
	int deleteByPrimaryKey(String recordFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.FSTU_CREDIT
	 * @mbggenerated  Mon Jun 29 16:58:22 CST 2015
	 */
	int insert(FstuCredit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.FSTU_CREDIT
	 * @mbggenerated  Mon Jun 29 16:58:22 CST 2015
	 */
	int insertSelective(FstuCredit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.FSTU_CREDIT
	 * @mbggenerated  Mon Jun 29 16:58:22 CST 2015
	 */
	List<FstuCredit> selectByExample(FstuCreditExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.FSTU_CREDIT
	 * @mbggenerated  Mon Jun 29 16:58:22 CST 2015
	 */
	FstuCredit selectByPrimaryKey(String recordFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.FSTU_CREDIT
	 * @mbggenerated  Mon Jun 29 16:58:22 CST 2015
	 */
	int updateByExampleSelective(@Param("record") FstuCredit record,
			@Param("example") FstuCreditExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.FSTU_CREDIT
	 * @mbggenerated  Mon Jun 29 16:58:22 CST 2015
	 */
	int updateByExample(@Param("record") FstuCredit record,
			@Param("example") FstuCreditExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.FSTU_CREDIT
	 * @mbggenerated  Mon Jun 29 16:58:22 CST 2015
	 */
	int updateByPrimaryKeySelective(FstuCredit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.FSTU_CREDIT
	 * @mbggenerated  Mon Jun 29 16:58:22 CST 2015
	 */
	int updateByPrimaryKey(FstuCredit record);
}