package com.pinde.sci.dao.base;

import com.pinde.sci.model.mo.GcpQcRecord;
import com.pinde.sci.model.mo.GcpQcRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GcpQcRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.GCP_QC_RECORD
	 * @mbggenerated  Mon Nov 17 14:26:38 GMT+08:00 2014
	 */
	int countByExample(GcpQcRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.GCP_QC_RECORD
	 * @mbggenerated  Mon Nov 17 14:26:38 GMT+08:00 2014
	 */
	int deleteByExample(GcpQcRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.GCP_QC_RECORD
	 * @mbggenerated  Mon Nov 17 14:26:38 GMT+08:00 2014
	 */
	int deleteByPrimaryKey(String qcFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.GCP_QC_RECORD
	 * @mbggenerated  Mon Nov 17 14:26:38 GMT+08:00 2014
	 */
	int insert(GcpQcRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.GCP_QC_RECORD
	 * @mbggenerated  Mon Nov 17 14:26:38 GMT+08:00 2014
	 */
	int insertSelective(GcpQcRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.GCP_QC_RECORD
	 * @mbggenerated  Mon Nov 17 14:26:38 GMT+08:00 2014
	 */
	List<GcpQcRecord> selectByExample(GcpQcRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.GCP_QC_RECORD
	 * @mbggenerated  Mon Nov 17 14:26:38 GMT+08:00 2014
	 */
	GcpQcRecord selectByPrimaryKey(String qcFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.GCP_QC_RECORD
	 * @mbggenerated  Mon Nov 17 14:26:38 GMT+08:00 2014
	 */
	int updateByExampleSelective(@Param("record") GcpQcRecord record,
			@Param("example") GcpQcRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.GCP_QC_RECORD
	 * @mbggenerated  Mon Nov 17 14:26:38 GMT+08:00 2014
	 */
	int updateByExample(@Param("record") GcpQcRecord record,
			@Param("example") GcpQcRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.GCP_QC_RECORD
	 * @mbggenerated  Mon Nov 17 14:26:38 GMT+08:00 2014
	 */
	int updateByPrimaryKeySelective(GcpQcRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.GCP_QC_RECORD
	 * @mbggenerated  Mon Nov 17 14:26:38 GMT+08:00 2014
	 */
	int updateByPrimaryKey(GcpQcRecord record);
}