package com.pinde.sci.dao.base;

import com.pinde.sci.model.mo.PubProjSearch;
import com.pinde.sci.model.mo.PubProjSearchExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PubProjSearchMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PROJ_SEARCH
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int countByExample(PubProjSearchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PROJ_SEARCH
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int deleteByExample(PubProjSearchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PROJ_SEARCH
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int deleteByPrimaryKey(String projSearchFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PROJ_SEARCH
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int insert(PubProjSearch record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PROJ_SEARCH
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int insertSelective(PubProjSearch record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PROJ_SEARCH
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	List<PubProjSearch> selectByExample(PubProjSearchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PROJ_SEARCH
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	PubProjSearch selectByPrimaryKey(String projSearchFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PROJ_SEARCH
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int updateByExampleSelective(@Param("record") PubProjSearch record,
			@Param("example") PubProjSearchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PROJ_SEARCH
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int updateByExample(@Param("record") PubProjSearch record,
			@Param("example") PubProjSearchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PROJ_SEARCH
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int updateByPrimaryKeySelective(PubProjSearch record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PROJ_SEARCH
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int updateByPrimaryKey(PubProjSearch record);
}