package com.pinde.sci.dao.base;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.pinde.sci.model.mo.PubPatientVisit;
import com.pinde.sci.model.mo.PubPatientVisitExample;

public interface PubPatientVisitMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PATIENT_VISIT
	 * @mbggenerated  Tue Nov 25 11:04:45 GMT+08:00 2014
	 */
	int countByExample(PubPatientVisitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PATIENT_VISIT
	 * @mbggenerated  Tue Nov 25 11:04:45 GMT+08:00 2014
	 */
	int deleteByExample(PubPatientVisitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PATIENT_VISIT
	 * @mbggenerated  Tue Nov 25 11:04:45 GMT+08:00 2014
	 */
	int deleteByPrimaryKey(String recordFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PATIENT_VISIT
	 * @mbggenerated  Tue Nov 25 11:04:45 GMT+08:00 2014
	 */
	int insert(PubPatientVisit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PATIENT_VISIT
	 * @mbggenerated  Tue Nov 25 11:04:45 GMT+08:00 2014
	 */
	int insertSelective(PubPatientVisit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PATIENT_VISIT
	 * @mbggenerated  Tue Nov 25 11:04:45 GMT+08:00 2014
	 */
	List<PubPatientVisit> selectByExampleWithBLOBs(
			PubPatientVisitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PATIENT_VISIT
	 * @mbggenerated  Tue Nov 25 11:04:45 GMT+08:00 2014
	 */
	List<PubPatientVisit> selectByExample(PubPatientVisitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PATIENT_VISIT
	 * @mbggenerated  Tue Nov 25 11:04:45 GMT+08:00 2014
	 */
	PubPatientVisit selectByPrimaryKey(String recordFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PATIENT_VISIT
	 * @mbggenerated  Tue Nov 25 11:04:45 GMT+08:00 2014
	 */
	int updateByExampleSelective(@Param("record") PubPatientVisit record,
			@Param("example") PubPatientVisitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PATIENT_VISIT
	 * @mbggenerated  Tue Nov 25 11:04:45 GMT+08:00 2014
	 */
	int updateByExampleWithBLOBs(@Param("record") PubPatientVisit record,
			@Param("example") PubPatientVisitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PATIENT_VISIT
	 * @mbggenerated  Tue Nov 25 11:04:45 GMT+08:00 2014
	 */
	int updateByExample(@Param("record") PubPatientVisit record,
			@Param("example") PubPatientVisitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PATIENT_VISIT
	 * @mbggenerated  Tue Nov 25 11:04:45 GMT+08:00 2014
	 */
	int updateByPrimaryKeySelective(PubPatientVisit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PATIENT_VISIT
	 * @mbggenerated  Tue Nov 25 11:04:45 GMT+08:00 2014
	 */
	int updateByPrimaryKeyWithBLOBs(PubPatientVisit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_PATIENT_VISIT
	 * @mbggenerated  Tue Nov 25 11:04:45 GMT+08:00 2014
	 */
	int updateByPrimaryKey(PubPatientVisit record);
	
}