package com.pinde.sci.dao.base;

import com.pinde.sci.model.mo.PubTrainUser;
import com.pinde.sci.model.mo.PubTrainUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PubTrainUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_TRAIN_USER
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int countByExample(PubTrainUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_TRAIN_USER
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int deleteByExample(PubTrainUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_TRAIN_USER
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int deleteByPrimaryKey(String recordFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_TRAIN_USER
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int insert(PubTrainUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_TRAIN_USER
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int insertSelective(PubTrainUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_TRAIN_USER
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	List<PubTrainUser> selectByExample(PubTrainUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_TRAIN_USER
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	PubTrainUser selectByPrimaryKey(String recordFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_TRAIN_USER
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int updateByExampleSelective(@Param("record") PubTrainUser record,
			@Param("example") PubTrainUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_TRAIN_USER
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int updateByExample(@Param("record") PubTrainUser record,
			@Param("example") PubTrainUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_TRAIN_USER
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int updateByPrimaryKeySelective(PubTrainUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_TRAIN_USER
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int updateByPrimaryKey(PubTrainUser record);
}