package com.pinde.sci.dao.base;

import com.pinde.sci.model.mo.PubTrain;
import com.pinde.sci.model.mo.PubTrainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PubTrainMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_TRAIN
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int countByExample(PubTrainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_TRAIN
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int deleteByExample(PubTrainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_TRAIN
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int deleteByPrimaryKey(String trainFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_TRAIN
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int insert(PubTrain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_TRAIN
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int insertSelective(PubTrain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_TRAIN
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	List<PubTrain> selectByExample(PubTrainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_TRAIN
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	PubTrain selectByPrimaryKey(String trainFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_TRAIN
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int updateByExampleSelective(@Param("record") PubTrain record,
			@Param("example") PubTrainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_TRAIN
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int updateByExample(@Param("record") PubTrain record,
			@Param("example") PubTrainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_TRAIN
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int updateByPrimaryKeySelective(PubTrain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.PUB_TRAIN
	 * @mbggenerated  Thu Aug 21 17:48:24 CST 2014
	 */
	int updateByPrimaryKey(PubTrain record);
}