package com.pinde.sci.dao.base;

import com.pinde.sci.model.mo.ResDoctorRecruit;
import com.pinde.sci.model.mo.ResDoctorRecruitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.pinde.sci.model.mo.ResDoctorRecruitWithBLOBs;

public interface ResDoctorRecruitMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.RES_DOCTOR_RECRUIT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	int countByExample(ResDoctorRecruitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.RES_DOCTOR_RECRUIT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	int deleteByExample(ResDoctorRecruitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.RES_DOCTOR_RECRUIT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	int deleteByPrimaryKey(String recruitFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.RES_DOCTOR_RECRUIT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	int insert(ResDoctorRecruitWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.RES_DOCTOR_RECRUIT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	int insertSelective(ResDoctorRecruitWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.RES_DOCTOR_RECRUIT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	List<ResDoctorRecruitWithBLOBs> selectByExampleWithBLOBs(
			ResDoctorRecruitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.RES_DOCTOR_RECRUIT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	List<ResDoctorRecruit> selectByExample(ResDoctorRecruitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.RES_DOCTOR_RECRUIT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	ResDoctorRecruitWithBLOBs selectByPrimaryKey(String recruitFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.RES_DOCTOR_RECRUIT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	int updateByExampleSelective(
			@Param("record") ResDoctorRecruitWithBLOBs record,
			@Param("example") ResDoctorRecruitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.RES_DOCTOR_RECRUIT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	int updateByExampleWithBLOBs(
			@Param("record") ResDoctorRecruitWithBLOBs record,
			@Param("example") ResDoctorRecruitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.RES_DOCTOR_RECRUIT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	int updateByExample(@Param("record") ResDoctorRecruit record,
			@Param("example") ResDoctorRecruitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.RES_DOCTOR_RECRUIT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	int updateByPrimaryKeySelective(ResDoctorRecruitWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.RES_DOCTOR_RECRUIT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	int updateByPrimaryKeyWithBLOBs(ResDoctorRecruitWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.RES_DOCTOR_RECRUIT
	 * @mbggenerated  Thu Aug 13 15:33:58 CST 2015
	 */
	int updateByPrimaryKey(ResDoctorRecruit record);
}