package com.pinde.sci.dao.base;

import com.pinde.sci.model.mo.SrmAchCopyrightAuthor;
import com.pinde.sci.model.mo.SrmAchCopyrightAuthorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrmAchCopyrightAuthorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.SRM_ACH_COPYRIGHT_AUTHOR
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	int countByExample(SrmAchCopyrightAuthorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.SRM_ACH_COPYRIGHT_AUTHOR
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	int deleteByExample(SrmAchCopyrightAuthorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.SRM_ACH_COPYRIGHT_AUTHOR
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	int deleteByPrimaryKey(String authorFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.SRM_ACH_COPYRIGHT_AUTHOR
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	int insert(SrmAchCopyrightAuthor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.SRM_ACH_COPYRIGHT_AUTHOR
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	int insertSelective(SrmAchCopyrightAuthor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.SRM_ACH_COPYRIGHT_AUTHOR
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	List<SrmAchCopyrightAuthor> selectByExample(
			SrmAchCopyrightAuthorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.SRM_ACH_COPYRIGHT_AUTHOR
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	SrmAchCopyrightAuthor selectByPrimaryKey(String authorFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.SRM_ACH_COPYRIGHT_AUTHOR
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	int updateByExampleSelective(@Param("record") SrmAchCopyrightAuthor record,
			@Param("example") SrmAchCopyrightAuthorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.SRM_ACH_COPYRIGHT_AUTHOR
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	int updateByExample(@Param("record") SrmAchCopyrightAuthor record,
			@Param("example") SrmAchCopyrightAuthorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.SRM_ACH_COPYRIGHT_AUTHOR
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	int updateByPrimaryKeySelective(SrmAchCopyrightAuthor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.SRM_ACH_COPYRIGHT_AUTHOR
	 * @mbggenerated  Thu Aug 21 17:48:25 CST 2014
	 */
	int updateByPrimaryKey(SrmAchCopyrightAuthor record);
}