package com.pinde.sci.dao.base;

import com.pinde.sci.model.mo.SrmFundScheme;
import com.pinde.sci.model.mo.SrmFundSchemeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrmFundSchemeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.SRM_FUND_SCHEME
	 * @mbggenerated  Mon Nov 10 13:57:38 CST 2014
	 */
	int countByExample(SrmFundSchemeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.SRM_FUND_SCHEME
	 * @mbggenerated  Mon Nov 10 13:57:38 CST 2014
	 */
	int deleteByExample(SrmFundSchemeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.SRM_FUND_SCHEME
	 * @mbggenerated  Mon Nov 10 13:57:38 CST 2014
	 */
	int deleteByPrimaryKey(String schemeFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.SRM_FUND_SCHEME
	 * @mbggenerated  Mon Nov 10 13:57:38 CST 2014
	 */
	int insert(SrmFundScheme record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.SRM_FUND_SCHEME
	 * @mbggenerated  Mon Nov 10 13:57:38 CST 2014
	 */
	int insertSelective(SrmFundScheme record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.SRM_FUND_SCHEME
	 * @mbggenerated  Mon Nov 10 13:57:38 CST 2014
	 */
	List<SrmFundScheme> selectByExample(SrmFundSchemeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.SRM_FUND_SCHEME
	 * @mbggenerated  Mon Nov 10 13:57:38 CST 2014
	 */
	SrmFundScheme selectByPrimaryKey(String schemeFlow);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.SRM_FUND_SCHEME
	 * @mbggenerated  Mon Nov 10 13:57:38 CST 2014
	 */
	int updateByExampleSelective(@Param("record") SrmFundScheme record,
			@Param("example") SrmFundSchemeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.SRM_FUND_SCHEME
	 * @mbggenerated  Mon Nov 10 13:57:38 CST 2014
	 */
	int updateByExample(@Param("record") SrmFundScheme record,
			@Param("example") SrmFundSchemeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.SRM_FUND_SCHEME
	 * @mbggenerated  Mon Nov 10 13:57:38 CST 2014
	 */
	int updateByPrimaryKeySelective(SrmFundScheme record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PDSCI.SRM_FUND_SCHEME
	 * @mbggenerated  Mon Nov 10 13:57:38 CST 2014
	 */
	int updateByPrimaryKey(SrmFundScheme record);
}